### ISSUE TITLE
Anleitung zur Installation und Konfiguration von ioBroker

### ISSUE THREAD

**Issue by Homoran** [ioBroker/ioBroker#10]

**Comment by sthufnagl** [comment]
Hi Rainer,
nicht schlecht, aber wo sind die Grafiken?

Steve

**Comment by Homoran** [comment]
Das ist es ja, da suche ich noch eine Möglichkeit, wie im Forum sie hochzuladen.
Auch die Struktur, wie ich sie gerne hätte bekomme ich nicht hin.

Ich glaube auch die internen Hyperlinks (Verweise) sind futsch

Danke für die ermutigende Unterstützung
Rainer
