### ISSUE TITLE
Following packages cannot be read: hm-ip

### ISSUE THREAD

**Issue by hopser2000** [ioBroker/ioBroker#103]
When I restart my ioBroker installation on my Pi (piVCCU image) I get the following warning:

warn: host.piVCCU warning: Following packages cannot be read: hm-ip

What's the matter? How can I fix that?

I also realized, that since that error occurs, I cannot connect my HMIP devices to the cloud adapter and let Alexa find (new) HMIP devices.

**Comment by Apollon77** [comment]
Sollte behoben sein. Sonst bitte repository unter Adapter neu laden

**Comment by hopser2000** [comment]
> Sollte behoben sein. Sonst bitte repository unter Adapter neu laden

Sorry für die Nachfrage, aber welches Repository nachladen meinst du?

**Comment by Apollon77** [comment]
Das repository Ist die adapterliste. Wird an sich einmal pro Tag automatisch geladen. Manuell geht unter Adapter immAdmin oben auf den reload Button (zwei Pfeile im Kreis)

**Comment by hopser2000** [comment]
Ah ja. Das hatte ich bereits gemacht. Stand heute morgen nur eine Aktualisierung für den Rega-Adapter, die ich installiert hab. Hatte danach iobroker vom Host aus mittels SuCo iobrokr restart neu gestartet. Warnmeldungen ist jetzt weg.
Trotzdem findet Alexa meine HMIP Geräte nicht, die ich im Cloud-Adapter eingetragen hab. Skill in Alexa ist installiert und mit iobroker Account verknüpft. Trotzdem ohne Erfolg. 
Im RPC Adaper sind meine HMIP Geräte aufgelistet. Anschließend im Cloud-Adapter über das Plus hinzugefügt und danach dann über Alexa App Geräte suchen lasssen. Nix....
Mache ich irgendwas falsch?

**Comment by hopser2000** [comment]
Alles klar. Danke trotzdem
