### ISSUE TITLE
additional color for  log

### ISSUE THREAD

**Issue by liv-in-sky** [ioBroker/ioBroker#105]
hi, would it be possible to add a new log level - maybe called "user" which is having another color - e.g. blue or green? 

it would be easier to add such a level to the self-made scripts for controlling_?

**Comment by Apollon77** [comment]
You want that in JavaScripts?! Then please create in JavaScript Adapter Repo. Or look at the logging scripts available in forum (think it was from ruhr70). There you can see how to add own colors to you logs.

**Comment by liv-in-sky** [comment]
ups - das war ja schnell ge-closed.
könntest du mir bitte  noch eine kurze antwort geben. ruhr (hab nicht viel im forum gefunden - post ist über 2 jahre alt )  hat sich mit javascript beschäftigt, ich bin aber eher ein blockly user. würde ich sowas gerne mal vorschlagen wollen, gehört das dann auch zum js adapter? mir ist nicht klar, wohin eigentlich blockly gehört bzw wo ich eine passende anfrage stellen soll.  
siehe bild: anstatt info - zusätzliche auswahl, z.b user1, user2, ...  und jeweils eine andere farbe im log dafür

**Comment by Apollon77** [comment]
Ja dann wäre es JavaScript Adapter.
