### ISSUE TITLE
Homematic Lichtsensor scheint nicht richtig erkannt zu werden.

### ISSUE THREAD

**Issue by aski71** [ioBroker/ioBroker#11]
Hallo,

der Lichtsensor wird offensichtlich nicht richtig in iobroker als Objekt angelegt.
Siehe auch Logs.

Viele Grüße
Alex

hm-rpc-0    2016-05-24 20:13:26 warn    Send this info to developer: {'type':'meta','meta':{'adapter':'hm-rpc','type':'paramsetDescription'},'common':{},'native':{'LUX':{'CONTROL':'LUXMETER.LUX','DEFAULT':0,'FLAGS':1,'ID':'LUX','MAX':100000,'MIN':0,'OPERATIONS':5,'TAB_ORDER':0,'TYPE':'FLOAT','UNIT':'Lux'}}}
hm-rpc-0    2016-05-24 20:13:26 info    setObject hm-rpc.meta.VALUES.HM-Sen-LI-O.LUXMETER.4
hm-rpc-0    2016-05-24 20:13:26 info    binrpc -> getParamsetDescription ['NEQ0322457:1','VALUES']
hm-rpc-0    2016-05-24 20:13:26 warn    Send this info to developer: {'type':'meta','meta':{'adapter':'hm-rpc','type':'paramsetDescription'},'common':{},'native':{'AES_KEY':{'DEFAULT':0,'FLAGS':0,'ID':'AES_KEY','MAX':127,'MIN':0,'OPERATIONS':1,'TAB_ORDER':8,'TYPE':'INTEGER','UNIT':''},'CONFIG_PENDING':{'DEFAULT':false,'FLAGS':9,'ID':'CONFIG_PENDING','MAX':true,'MIN':false,'OPERATIONS':5,'TAB_ORDER':2,'TYPE':'BOOL','UNIT':''},'DEVICE_IN_BOOTLOADER':{'DEFAULT':false,'FLAGS':9,'ID':'DEVICE_IN_BOOTLOADER','MAX':true,'MIN':false,'OPERATIONS':5,'TAB_ORDER':6,'TYPE':'BOOL','UNIT':''},'LOWBAT':{'DEFAULT':false,'FLAGS':9,'ID':'LOWBAT','MAX':true,'MIN':false,'OPERATIONS':5,'TAB_ORDER':3,'TYPE':'BOOL','UNIT':''},'RSSI_DEVICE':{'DEFAULT':0,'FLAGS':1,'ID':'RSSI_DEVICE','MAX':2147483647,'MIN':-2147483648,'OPERATIONS':5,'TAB_ORDER':4,'TYPE':'INTEGER','UNIT':''},'RSSI_PEER':{'DEFAULT':0,'FLAGS':1,'ID':'RSSI_PEER','MAX':2147483647,'MIN':-2147483648,'OPERATIONS':5,'TAB_ORDER':5,'TYPE':'INTEGER','UNIT':''},'STICKY_UNREACH':{'DEFAULT':false,'FLAGS':25,'ID':'STICKY_UNREACH','MAX':true,'MIN':false,'OPERATIONS':7,'TAB_ORDER':1,'TYPE':'BOOL','UNIT':''},'UNREACH':{'DEFAULT':false,'FLAGS':9,'ID':'UNREACH','MAX':true,'MIN':false,'OPERATIONS':5,'TAB_ORDER':0,'TYPE':'BOOL','UNIT':''},'UPDATE_PENDING':{'DEFAULT':false,'FLAGS':9,'ID':'UPDATE_PENDING','MAX':true,'MIN':false,'OPERATIONS':5,'TAB_ORDER':7,'TYPE':'BOOL','UNIT':''}}}
hm-rpc-0    2016-05-24 20:13:26 info    setObject hm-rpc.meta.VALUES.HM-Sen-LI-O.MAINTENANCE.4
hm-rpc-0    2016-05-24 20:13:25 info    binrpc -> getParamsetDescription ['NEQ0322457:0','VALUES']
hm-rpc-0    2016-05-24 20:13:25 warn    No image for 'HM-Sen-LI-O' found.
hm-rpc-0    2016-05-24 20:13:25 info    binrpc <- newDevices 3

**Comment by Apollon77** [comment]
Wenn das noch aktuell ist bitte unter https://github.com/ioBroker/ioBroker.hm-rpc nochmals mit aktuellen Infos und Logs mit den aktuellsten hm-rpc Version einstellen. Danke

**Comment by aski71** [comment]
Sieht jetzt gut alles aus. Danke.
