### ISSUE TITLE
Provide autocompletion for `iobroker` commands

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker#114]
See https://superuser.com/a/523574 how to (basically) do it. We need to find a way to update those when commands are added/changed. Maybe this should be in the js-controller then?

**Comment by AlCalzone** [comment]
Every time a command is changed, the controller must be updated. So it would make sense to have the logic there.

**Comment by foxriver76** [comment]
https://github.com/ioBroker/ioBroker.js-controller/pull/1181
