### ISSUE TITLE
[Linux] New installer: Error EACCES opening ports < 1024

### ISSUE THREAD

**Issue by Stabilostick** [ioBroker/ioBroker#116]
Wenn man nach dem neuen Setup mit install.sh im JavaScrip-Adapter auf Ports < 1024 binden möchte, kann das aktuell mit der Fehlermeldung EACCES fehlschlagen. Nicht-ROOT-User dürfen auf Ports <1024 nämlich nicht binden.

Hier hilft unter Debian z.B. folgendes:

```
sudo apt-get update
sudo apt-get install libcap2-bin
sudo setcap cap_net_bind_service=+eip $(eval readlink -f 'which node')
```

Ggf. kann das auch für Adapter, die Ports < 1024 aufmachen, nützlich sein. Z.B. der Modbus-Adapter im Slave-Modus. Der braucht 0.0.0.0:502

Bitte prüfen und ggf. im install.sh berücksichtigen.

**Comment by AlCalzone** [comment]
Closed by #119
