### ISSUE TITLE
On Windows subsystems installation is working but no autostart and no adding/changing of addapter possible

### ISSUE THREAD

**Issue by frankjoke** [ioBroker/ioBroker#117]
AlCalzone, 
If you open an shell to Linux  (in my case it's Ubuntu) you can install iobroker but it will not autostart.

If started manually with iobroker start it will start and run (you can access it with localhost:8081) but I cannot add adapters and do anything which runs npm.

p.s.: The subsystem icon runs automatically an bash shell as root user. I am not sure how user management in the subsystem works...

**Comment by AlCalzone** [comment]
Can you please post the output of `ls -la` directly after installation?

**Comment by Gaspode69** [comment]
I guess this can be closed.
Meanwhile, under WSL npm can be used without problems.
Furthermore, autostarting daemons is afaik not part of the WSL architecture.
MS suggests to use the task scheduler to autostart daemons together with the Windows PC under WSL, see:
https://learn.microsoft.com/en-us/answers/questions/1163405/automatically-starting-a-service-when-a-wsl-instan
