### ISSUE TITLE
Neuer Adapter

### ISSUE THREAD

**Issue by appzer** [ioBroker/ioBroker#12]
Hallo,

mein Name ist Kevin.
Auf Basis dieses Paketes https://www.npmjs.com/package/iobroker.pushover

Habe ich für den Service von Pushsafer.com einen neuen Adapter erstellt.

Ich würde Sie bitten, diesen mit auf Ihren Seiten (iobroker.net, NPM, Github) anzubieten.

Pushsafer.com bietet einige Vorteile gegenüber Pushover und ist ein weiteres nützliches Tool für iobroker.
z.B. bietet Pushsafer Client Apps für iOS, Android und Windows 10 sowie Webpush für Chrome und Firefox an.
Desweiteren kann man seine Push Nachrichten weiter personalisieren, indem man Icon, Sound, Vibration einstellen kann.

Ich bitte um kurzes Feedback! ZIP Datei habe ich hier mit angehängt.

[ioBroker.pushsafer.zip](https://github.com/ioBroker/ioBroker/files/480242/ioBroker.pushsafer.zip)

**Comment by appzer** [comment]
Hallo Bluefox,

es wäre super, wenn du es bei iobroker (npm und github) veröffentlichst, so ist alles an einer Stelle.
Wenn es mal ein Update geben sollte, dann gebe ich über git Bescheid.

Grüße Kevin

**Comment by appzer** [comment]
wenn alles veröffentlicht ist, werde ioBroker auf pushsafer erwähnen
Bis dahin
Gruß Kevin

**Comment by GermanBluefox** [comment]
Hallo Kevin,
es gibt kein Private Key Bild.
Wills du dass ich das lösche oder hast du noch Bild für mich?
Über Usage:
https://github.com/ioBroker/ioBroker.pushsafer/blob/master/README.md#usage

Gruß,
Bluefox

2016-09-19 16:43 GMT+02:00 Kevin <notifications@github.com>:

**Comment by appzer** [comment]
anbei
![screen0](https://cloud.githubusercontent.com/assets/3443312/18647133/daf2c0d8-7eb4-11e6-9386-56f8d0ef904c.png)

Gruß Kevin

**Comment by appzer** [comment]
habe die Readme geändert und einen Pull Request eröffnet

Gruß Kevin

**Comment by Apollon77** [comment]
fixed, oder ?!
