### ISSUE TITLE
SCHEMA.md Adapter aktualisieren

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/ioBroker#120]
https://github.com/ioBroker/ioBroker/blob/master/doc/SCHEMA.md#adapter

- [ ] Im Repo-Checker wird "title" als Pflichtfeld deklariert, im Schema ist es aber als deprecated eingetragen und dafür "titleLang" als Pflichtfeld. Siehe: https://github.com/ioBroker/ioBroker.repochecker/issues/1
- [ ] common.docs wurde nicht beschrieben
- [ ] common.keywords wurde nicht beschrieben
- [ ] common.readme wurde nicht beschrieben
- [ ] common.type wurde nicht beschrieben
- [ ] beim common.welcomeScreen fehlt common.welcomeScreen.order
- [ ] common.welcomeScreenPro wurde nicht beschrieben
- [ ] common.allowInit ist doppelt vorhanden
- [ ] common.schedule wurde nicht beschrieben
- [ ] common.dependencies wurde nicht beschrieben
- [ ] common.main wurde nicht beschrieben
- [ ] common.adminTab.fa-icon wurde nicht beschrieben
- [ ] common.engineTypes wurde nicht beschrieben
- [ ] common.wakeup ist drin, wurde aber nicht beschrieben
- [ ] common.npmLibs wurde nicht beschrieben
- [ ] common.wwwDontUpload wurde nicht beschrieben
- [ ] common.localLinks wurde nicht beschrieben
- [ ] bessere Ordnung, damit man überhaupt was findet (alphabetisch?)

**Comment by AlCalzone** [comment]
- [ ] common.custom wird nicht beschrieben. Bei welchen Objekten darf es auftreten?
