### ISSUE TITLE
Nach Update auf 0.9.1 werden Services teilweise nicht angezeigt

### ISSUE THREAD

**Issue by sharky-os** [ioBroker/ioBroker#123]
Habe von 0.9.0 auf 0.9.1 geupdatet, weil ich auch die Probleme mit dem Batterie Service hatte.
Nun funktioniert zwar alles, aber mir werden in der Adapterkonfig die Services teilweise nicht mehr angezeigt,
obwohl sie in Homekit immernoch vorhanden sind und ganz normal funkionieren. Ich kann auch  keinen Zusammenhang erkennen, warum einige angezeigt werden und andere nicht.

Gruß Marco

**Comment by AlCalzone** [comment]
Ich glaube das ist das falsche repo. Bitte im richtigen Adapter-Repo berichten!

**Comment by sharky-os** [comment]
Sorry. Danke für den Hinweis.
