### ISSUE TITLE
zusätzliche Module für Node Red?

### ISSUE THREAD

**Issue by thatso** [ioBroker/ioBroker#124]
Ich habe ioBroker unter Raspian Stretch Lite nach [dieser Anleitung](http://www.iobroker.net/docu/?page_id=8323&lang=de) aufgesetzt und den Node Red Adapter installiert.
Obwohl [hier](http://www.iobroker.net/docu/?page_id=4284&lang=de) erklärt wird, weitere Module manuell zu ergänzen, habe ich inzwischen herausgefunden, daß stattdessen diese auf der Konfigurationsseite eingetragen werden sollen und auch nicht innerhalb der Node Red Palette installiert werden dürfen.
Die eingetragenen Module tauchen zwar im Verzeichnis
`/opt/iobroker/node_modules/iobroker.node-red/node_modules`
auf, allerdings nicht innerhalb Node Red selbst.
Neustarts des Adapters bzw. des kompletten OS haben daran nichts geändert.

**Comment by Apollon77** [comment]
Bitte issue Im Node-red repo anlegen
