### ISSUE TITLE
fix_installation.sh

### ISSUE THREAD

**Issue by Seqway** [ioBroker/ioBroker#129]
I tried to run this script and got an error message:

`curl -sL https://github.com/ioBroker/ioBroker/blob/master/fix_installation.sh | bash -
bash: Zeile 7: Syntaxfehler beim unerwarteten Wort `newline'
bash: Zeile 7: `<!DOCTYPE html>'`

**Comment by AlCalzone** [comment]
Der Link ist falsch.
```bash
curl -sL https://raw.githubusercontent.com/ioBroker/ioBroker/stable-installer/fix_installation.sh | bash -
```

**Comment by Apollon77** [comment]
@Seqway Es kommt heute noch die offizielle Forum Ankündigung mit genau diesem finalen Link. Wo ist der andere Link her?
