### ISSUE TITLE
The npm link seems to be broken

### ISSUE THREAD

**Issue by torwag** [ioBroker/ioBroker#13]
Hi,
the given npm link seems to be broken. The widget indicates "invalid". trying to install iobroker via
npm iobroker.iopbroker as described results in:

404 Registry returned 404 for GET on https://registry.npmjs.org/iobroker.iobroker
npm ERR! 404 
npm ERR! 404  'iobroker.iobroker' is not in the npm registry.

**Comment by GermanBluefox** [comment]
You should use just
sudo npm i iobroker --unsafe-perm


13 Янв 2017 г. 10:04 пользователь "Torwag" <notifications@github.com>
написал:
