### ISSUE TITLE
Xiaomi Honeywell Gas Leakage Sensor JTQJ-BF-01LM/BW

### ISSUE THREAD

**Issue by ericsboro** [ioBroker/ioBroker#130]
Is there a way to add support of Xiaomi Honeywell Gas Leakage Sensor JTQJ-BF-01LM/BW?

Sensor successfully connected via CC2531 as router, but it was not identified properly: it appeared as "lumi.sensor_natgas", but without Sensor icon in Zigbee adapter. In Objects it appeared as one string without "state" options.

**Comment by GermanBluefox** [comment]
Please make your request here: https://github.com/ioBroker/ioBroker.zigbee/issues
