### ISSUE TITLE
ble Adapter läuft nach Insatllations Fixer nicht mehr

### ISSUE THREAD

**Issue by ihavenonick** [ioBroker/ioBroker#131]
sudo setcap cap_net_raw+eip $(eval readlink -f which node)
muss ausgeführt werden, damit das wieder passt

**Comment by Ilovegym66** [comment]
bei musste die Schreibweise so heissen:
sudo setcap 'cap_net_raw,cap_net_admin+eip' $(readlink -f $(which node))

mit der obigen wollte es nicht..

**Comment by ihavenonick** [comment]
So ist es zumindest auch in der ble Doku angegeben und läuft bei mir.

**Comment by Ilovegym66** [comment]
bei mir ist das immer etwas komplizierter :-) Liegt wohl am System und Node? LInux Mint 18.3, Node 8.15, NPM 6.8.0.
Hab das in Verbindung mit dem Amazon-Dash Adapter gehabt und diese Lösung hier half:
https://www.blogging-it.com/node-pcap-module-error-socket-operation-not-permitted-fehler-wenn-pcapsession-geoeffnet-wird/programmierung/javascript/nodejs.html

**Comment by ihavenonick** [comment]
NPM 6.8 wird auch nicht wirklich empfohlen, sollte max 6.5 sein. Ob da der Unterschied liegt, entzieht sich aber meinen bescheidenen Linux Kenntnissen.
Egal, Apollon wird das schon richtem

**Comment by Apollon77** [comment]
Es sind aktuell keine probleme mit npm 6.8 bekannt, also die Aussage ist falsch - desweiteren hat npm damit nichts zu tun.
Also node und npm ist ok. Der obigen Befehl sollte für ble und amazon-dash helfen. Wir hinzugefügt

**Comment by ihavenonick** [comment]
Dass das nicht wirklich was damit zu tun hat ist klar, gibt aber viele Beiträge dazu im Forum wo eher nicht zur 6.8 geraten wird. 
Das eigentlich Problem ist ja erkannt und wird behoben, somit mach ich hier mal zu.

**Comment by Apollon77** [comment]
Wir machen zu WENN es behoben wird. :-)
Von der 6.8 wurde "abgeraten" weil die Frage ein paar Stunden nach dem Releease kam und npm auch nicht unbedingt immer für "perfekte Fehlerfreie Software" bekannt ist :-)

**Comment by ihavenonick** [comment]
OK, dachte nur, der der es geöffnet hat, sollte das auch schließen. Da Du da dran bist, ist es für mich s gut wie erledigt.

**Comment by Ilovegym66** [comment]
Web Adapter lief nicht mehr wenn der Port <1024 war, ein 
sudo setcap 'cap_net_bind_service=+ep' $(readlink -f $(which node))
half.
Bitte noch in den Fixer einbauen.

**Comment by Apollon77** [comment]
... und in den Installer :-)

**Comment by Apollon77** [comment]
Strange ... 		

sudo setcap cap_net_bind_service=+eip $(eval readlink -f `which node`)

ist im Fixer bereits enthalten

**Comment by Apollon77** [comment]
Also verifiziert ein getcap $(eval readlink -f `which node`) gibt bei mir

/usr/bin/node = cap_net_bind_service+eip

war also schon gesetzt. Keine Ahnung was das bei dir war

**Comment by Ilovegym66** [comment]
ja, komisch, bei mir:
getcap $(eval readlink -f `which node`)
/usr/bin/node = cap_net_bind_service+ep

warum kommt bei dir ein +eip ?
ich hab das hier für den Amazondash gebraucht
sudo setcap 'cap_net_raw,cap_net_admin+eip' $(readlink -f $(which node))

**Comment by Apollon77** [comment]
Da muss ich wegen eip vs ep wohl nochmal checken.

**Comment by Apollon77** [comment]
Then we have it ... the "eip" (according to Google) was wrong ... ep is correct, I will change it in installer and fixer

**Comment by Apollon77** [comment]
Nope ... eip should also work ... the i just add it also for "Inherited processes"

**Comment by Apollon77** [comment]
Bzw versuche mal:
		sudo setcap cap_net_bind_service=+eip $(eval readlink -f `which node`)

**Comment by Apollon77** [comment]
Kannst Du mal versuchen ob bei dir das set mit eip auch noch tut? (setze es einfach nochmal "drüber")

**Comment by Apollon77** [comment]
Und nochmal kommando zurück. Das "=" muss raus sonst wird das zurückgesetzt.

Also

 sudo setcap cap_net_bind_service+eip $(eval readlink -f `which node`)

IST korrekt
