### ISSUE TITLE
Echo Input wird nicht richtig erkannt

### ISSUE THREAD

**Issue by MyzerAT** [ioBroker/ioBroker#140]
Im iobroker wird der Echo Input unter Objkte/Alexa2.0/Echo-Devices zwar erkannt aber es fehlen Datenpunkte wie zb. Commands oder Routnies  

![grafik](https://user-images.githubusercontent.com/47501072/53694633-d7c49080-3db1-11e9-8ec3-de03536d489a.png)

![](https://forum.iobroker.net/assets/uploads/files/1551610937992-bbc2c14e-0634-4be5-a6f4-4d610c8e4352-grafik.png)

**Comment by AlCalzone** [comment]
Falsches Repo. Das Issue gehört ins [ioBroker.alexa2-Repo](https://github.com/Apollon77/ioBroker.alexa2).
