### ISSUE TITLE
Nach Fixer install keine Adapter updates mehr möglich

### ISSUE THREAD

**Issue by passuff** [ioBroker/ioBroker#142]
Ich habe aufgrund des stop/Start issues den install fixer ausgeführt. Stop/start funktionieren jetzt, leider kann ich keine Adapter mehr aktualisieren:

` $ ./iobroker upgrade javascript
Update javascript from @4.1.7 to @4.1.8
NPM version: 6.4.1
npm install iobroker.javascript@4.1.8 --production --save --prefix "/opt/iobroker" (System call)
npm

WARN
deprecated
coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm

WARN

checkPermissions
Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/long-timeout
npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/moment
npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/moment-timezonenpm WARN
checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/object-keysnpm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/define-properties
npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/is-nan
npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/cron-parser
npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/sorted-array-functions
npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/@types/node
npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript
npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules
npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.javascript/node_modules/@types

npm

WARN
react-beautiful-dnd@9.0.2 requires a peer of react@^16.3.1 but none is installed. You must install peer dependencies yourself.
npm
WARN react-motion@0.5.2 requires a peer of react@^0.14.9 || ^15.3.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.npm WARN react-redux@5.1.1 requires a peer of react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0 but none is installed. You must install peer dependencies yourself.

npm

ERR!
path
/opt/iobroker/node_modules/iobroker.javascript/node_modules/long-timeoutnpm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/opt/iobroker/node_modules/iobroker.javascript/node_modules/long-timeout'
npm ERR! { Error: EACCES: permission denied, access '/opt/iobroker/node_modules/iobroker.javascript/node_modules/long-timeout'
npm ERR! stack: 'Error: EACCES: permission denied, access '/opt/iobroker/node_modules/iobroker.javascript/node_modules/long-timeout'',
npm ERR! errno: -13,
npm ERR! code: 'EACCES',
npm ERR! syscall: 'access',
npm ERR! path: '/opt/iobroker/node_modules/iobroker.javascript/node_modules/long-timeout' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm

ERR!
A complete log of this run can be found in:npm
ERR! /home/iobroker/.npm/_logs/2019-03-03T19_04_36_694Z-debug.log
ERROR: host.IoBroker-VM-Debian Cannot install iobroker.javascript@4.1.8: 243
ERROR: process exited with code 25 `

**Comment by AlCalzone** [comment]
Kannst du bitte den Inhalt von `/opt/iobroker/INSTALLER_INFO.txt` posten?

**Comment by AlCalzone** [comment]
Und die Ausgabe von
`ls -la /opt/iobroker/node_modules/iobroker.javascript/node_modules/`

**Comment by passuff** [comment]
habe den Fixer nach einem reboot noch einmal durchlaufen lassen. Ich kann die Adapter wieder aktualisieren. Ich hoffe es bleibt jetzt bei diesem Zustand. Hier noch die Auszüge:

`Fixer version: 2019-02-25
Fix date 2019-03-01
init system: systemd
Autostart: systemd
Fixer version: 2019-03-03
Fix date 2019-03-03
init system: systemd
Autostart: systemd
`

`root@IoBroker-VM-Debian:~# ls -la /opt/iobroker/node_modules/iobroker.javascript/node_modules/
insgesamt 52
drwxr-xr-x 13 iobroker iobroker 4096 Mär  3 22:02 .
drwxr-xr-x  9 iobroker iobroker 4096 Mär  3 22:02 ..
drwxr-xr-x  2 iobroker iobroker 4096 Mär  3 22:02 .bin
drwxr-xr-x  4 iobroker iobroker 4096 Mär  3 22:01 cron-parser
drwxr-xr-x  3 iobroker iobroker 4096 Mär  3 22:01 define-properties
drwxr-xr-x  3 iobroker iobroker 4096 Mär  3 22:01 is-nan
drwxr-xr-x  2 iobroker iobroker 4096 Mär  3 22:01 long-timeout
drwxr-xr-x  5 iobroker iobroker 4096 Mär  3 22:01 moment
drwxr-xr-x  4 iobroker iobroker 4096 Mär  3 22:01 moment-timezone
drwxr-xr-x  4 iobroker iobroker 4096 Dez 17 23:21 node-schedule
drwxr-xr-x  3 iobroker iobroker 4096 Mär  3 22:01 object-keys
drwxr-xr-x  2 iobroker iobroker 4096 Mär  3 22:01 sorted-array-functions
drwxr-xr-x  3 iobroker iobroker 4096 Mär  3 22:02 @types
`

**Comment by AlCalzone** [comment]
Danke, ich glaube ich weiß was das Problem war.
