### ISSUE TITLE
iobroker has no right to root

### ISSUE THREAD

**Issue by Mr-REM-Esq** [ioBroker/ioBroker#151]
I installed the ioBroker using the recommended script (curl -sL https://raw.githubusercontent.com/ioBroker/ioBroker/stable-installer/installer.sh | bash -). Now the ioBroker starts added in autostart, but there is a problem. The user where ioBroker is running under is not root. Its name is "iobroker". This user does not have many permissions (for example, HAM doesn't work correctly). How to make ioBroker have all the rights?

**Comment by Apollon77** [comment]
What rights especially are needed? If he needs to access the root HAM directory then give rights 777 to this directory or use chown to change owner to iobroker.iobroker

**Comment by Mr-REM-Esq** [comment]
Homebridge does not start.

<img width="1004" alt="Снимок экрана 2019-03-13 в 1 15 55" src="https://user-images.githubusercontent.com/42520242/54239893-952b5280-452d-11e9-8c9b-523b9040d381.png">


<img width="1437" alt="Снимок экрана 2019-03-13 в 1 10 03" src="https://user-images.githubusercontent.com/42520242/54239806-509fb700-452d-11e9-84c6-16ba1beb0492.png">

drwxr-xr-x 6 iobroker iobroker 4096 мар 13 00:59 .
drwxr-xr-x 6 root     root     4096 фев 18 13:40 ..
-rw-r--r-- 1 iobroker iobroker  220 май 15  2017 .bash_logout
-rw-r--r-- 1 iobroker iobroker 3526 май 15  2017 .bashrc
drwx------ 3 iobroker iobroker 4096 фев 18 13:47 .config
drwxr-xr-x 4 iobroker iobroker 4096 мар 13 01:07 .homebridge
drwxr-xr-x 5 iobroker iobroker 4096 мар 11 00:30 .node-gyp
drwxr-xr-x 5 iobroker iobroker 4096 мар  5 18:30 .npm
-rw-r--r-- 1 iobroker iobroker  675 май 15  2017 .profile
roman@iobroker:/home/iobroker$ 

drwxr-xr-x 4 iobroker iobroker 4096 мар 13 01:07 .
drwxr-xr-x 6 iobroker iobroker 4096 мар 13 00:59 ..
drwxr-xr-x 2 iobroker iobroker 4096 мар 13 01:08 accessories
-rw-r--r-- 1 iobroker iobroker  359 мар 13 01:07 auth.json
-rw-r--r-- 1 iobroker iobroker  358 мар 13 01:01 config.json
drwxr-xr-x 2 iobroker iobroker 4096 мар 13 01:07 persist
roman@iobroker:/home/iobroker/.homebridge$

**Comment by Mr-REM-Esq** [comment]
I reinstalled the homebridge and now it works!
