### ISSUE TITLE
Xiaomi Air Conditioner Gateway

### ISSUE THREAD

**Issue by JvB94** [ioBroker/ioBroker#171]
Hi,

ich hatte es schon bei dem Mi Home Adapter probiert allerdings aber keinen erfolg gehabt.
Würde mich mega darüber freuen wenn https://github.com/ioBroker/ioBroker.mihome/issues/48 als Plugin eingebunden werden würde damit ich die Klimaanlage z. B. mit Alexa Steuern kann.

Unterstütze natürlich gerne wenn ihr Logs etc. braucht.

LG

**Comment by Apollon77** [comment]
Wenn schon ein issue existiert bringt es wenig noch eins wo anders zu öffnen. Adapter requests gehören auch in ein anderes Projekt (ioBroker/AdapterRequests).
