### ISSUE TITLE
'iobroker.inst' is not in the npm repository

### ISSUE THREAD

**Issue by andrico21** [ioBroker/ioBroker#175]
Hi. After some numerous retries to install (with official 'script' way) and update iobroker on RPi3/Raspbian I've got it work itself, but cannot do anything with npm.
'npm audit fix' fails with lock package errors suggesting to run 'npm install', 'npm install' fails with "'iobroker.inst' is not in the npm repository" error - so I cannot do anything...
Is there a way to fix "'iobroker.inst' is not in the npm repository" or it is some kind of expected behavior?

**Comment by andrico21** [comment]
log files attached:
[NPMlogs.zip](https://github.com/ioBroker/ioBroker/files/3330488/NPMlogs.zip)

**Comment by AlCalzone** [comment]
> but cannot do anything with npm.

Please explain what exactly you cannot do with npm.

The root package "iobroker.inst" or how it is called, is not supposed to be installed and in fact does not exist in the npm registry - so the error is expected. It is only used to save which adapters are installed, so npm does not delete them while installing packages.

The warning from `npm audit` can be ignored.

**Comment by andrico21** [comment]
@AlCalzone thanks for fast reply.
I've just tried to tide up the installation, check it any dependencies is unmet, clean old packages etc...

first, after updating iobroker to latest version I got errors below:
npm ERR!     Invalid: lock file's iobroker.admin@3.6.2 does not satisfy iobroker.admin@^3.6.3
npm ERR!     Invalid: lock file's iobroker.discovery@1.3.0 does not satisfy iobroker.discovery@^2.0.0
as well as lot of dependencies 'missing' (log attached above)...
npm view is not working, npm install is not working etc...

**Comment by andrico21** [comment]
On some forum I've seen recommendation to run npm i with --unsafe-perm option, when I tried to do so I've got just:
npm ERR! code ELIFECYCLE
npm ERR! errno 100
npm ERR! iobroker.inst@2.0.3 postinstall: `node lib/install.js`
npm ERR! Exit status 100
npm ERR!
npm ERR! Failed at the iobroker.inst@2.0.3 postinstall script.

2019-06-26T13_49_49_585Z-debug.log

**Comment by AlCalzone** [comment]
> npm ERR! Invalid: lock file's iobroker.admin@3.6.2 does not satisfy iobroker.admin@^3.6.3
> npm ERR! Invalid: lock file's iobroker.discovery@1.3.0 does not satisfy iobroker.discovery@^2.0.0
> as well as lot of dependencies 'missing' (log attached above)...

Try deleting `/opt/iobroker/package-lock.json`.

In general you should not have to check dependencies yourself. If you only ever install adapters with the official commands and the admin UI, `npm` takes care of organizing the dependencies.

**Comment by andrico21** [comment]
> If you only ever install adapters with the official commands and the admin UI, `npm` takes care of organizing the dependencies.
Unfortunately no with https://www.npmjs.com/package/iobroker.lgtv package - a lot of dependencies dropped warnings about deprecation, some directly reported I need to install dependencies myself.

Thanks much @AlCalzone, removing /opt/iobroker/package-lock.json with npm rebuild solved most of the issues with npm: now I'm able to audit/ls etc. So the solution is to delete package-lock.json and to rebuild npm modules.

**Comment by AlCalzone** [comment]
> Unfortunately no with https://www.npmjs.com/package/iobroker.lgtv package - a lot of dependencies dropped warnings about deprecation

I would be careful with upgrading dependencies manually. Even if they are deprecated, the adapter might depend on a specific version to work correctly. It would probably be better to report this to the adapter dev, so he can take care of upgrading his dependencies to non-deprecated ones.
