### ISSUE TITLE
Feature request: State Overwrite

### ISSUE THREAD

**Issue by Goersch** [ioBroker/ioBroker#18]
Hello, 

would be helpful to be able to "overwrite" the state/level/etc. of an object.

Example for better understanding what I mean:
- in Tab "Objects" opening the configuration dialog of e.g. a state
- checkbox "overwrite" with possibility to enter the "overwrite-value"
- now all external writes to this state are blocked and the state will always have the value "overwrite-value" as long as the checkbox is checked

This function is also called "force".

**Comment by Apollon77** [comment]
What would be the benefit and for what you want to use it?

**Comment by Goersch** [comment]
2 benefits:
- to void script functions for selected devices. E.g. opening a window will not start a script, but all other do
- easier testing of scripts

**Comment by Apollon77** [comment]
JavaScript Adapter already has a "simulation"-mode and Debug mode where state changes are not written. Especially for testing. Do you know that?

in general such things are normally done by special States e.g. from JavaScript Adapter that are included then in the scripts and are checked before any action is done.

Please put that idea in the Forum for further discussion to see if other users see that usefull too.

**Comment by GermanBluefox** [comment]
I will close this request, because it is all possible somehow.

**Comment by Goersch** [comment]
I agree :)
