### ISSUE TITLE
"Log herunterladen" button missing

### ISSUE THREAD

**Issue by passuff** [ioBroker/ioBroker#186]
Since I made some updates the button disappeared. My config is as following:

Platform : linux
Architecture : x64
CPUs : 1
Speed : 1799 MHz
Model : Intel(R) Xeon(R) CPU E5-2403 0 @ 1.80GHz
RAM : 3.8 GB
System uptime : 6d. 02:26:23
Node.js : v10.16.2
Disk size : 11.7 GiB
Disk free : 6.4 GiB
NPM : v6.9.0
adapters count : 286

**Comment by AlCalzone** [comment]
1. This belongs in the admin repo
2. I think this is fixed (I see the button in 2.0.x)
/cc @Apollon77
