### ISSUE TITLE
Working with tablets

### ISSUE THREAD

**Issue by Goersch** [ioBroker/ioBroker#19]
Hello,

working with iobroker on a tablet (in my case iPad) is sometimes very "hard". 

It would help to have a "open" and "close" button on the object tab, which opens/closes the folder of a selected object. Right now it is only possible to open/close all folders.

**Comment by Apollon77** [comment]
Is this an Admin topic? Then it should go into "ioBroker.admin" ... or in general we currently use Trello for feature requests and such at the moment ... or the forum to first discuss it.
http://forum.iobroker.net/viewtopic.php?f=24&t=4733
