### ISSUE TITLE
Handbuch - Win Download Link broken

### ISSUE THREAD

**Issue by snador1977** [ioBroker/ioBroker#196]
The Download Link for the Windows Installer (http://download.iobroker.org/ioBrokerInstaller.0.5.0.exe) from Documentation does not exist...

**Comment by Stabilostick** [comment]
All official ioBroker downloads are at [this URL](https://www.iobroker.net/#en/download).

 Can you please tell us the location where you found the not working link?

**Comment by Stabilostick** [comment]
Closed because no feedback.
