### ISSUE TITLE
Fix for recent npm issues

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker#199]
## The problem
`setfacl` and adding the user to `iobroker` group allows us to control the default permissions inside  `/opt/iobroker`:
![grafik](https://user-images.githubusercontent.com/17641229/65545804-6b100f80-df16-11e9-8068-f7b9dcdc9cb8.png)

These permissions are additionally masked by the mode set by `chmod` (see MASK), so setting `755` effectively disables write access for the group members. Now, `npm` is nice enough to ignore the default permissions we set and does just that.

What happens for our users is the following:
0. The fixer restores permissions, so the files in `node_modules` belong to `iobroker:iobroker`.
1. User executes `npm` with his default user, be it root or `pi` or whatever. **IF** that succeeds, some files now belong to `root` or `pi`. This user has access to the files of `iobroker`, but not vice versa.
2. When the Admin UI now tries to install an adapter, `iobroker` no longer has access because the files belong to another user.

What we did with ACLs and group access and so on does not matter anyways, because `npm` removes write access for the group. Back to square 1...

## The solution
Prevent `npm` from being executed as NOT iobroker inside `/opt/iobroker`. Probably the cleanest solution is putting this (with the correct paths of course) in `~/.bashrc`:
![grafik](https://user-images.githubusercontent.com/17641229/65546718-5d5b8980-df18-11e9-8e16-9017131e4295.png)
This causes `npm` to invoke this function instead of the binary. We now test if we're inside `/opt/iobroker` and call the original `npm` as `iobroker`. If not, we just call the original `npm`.

We might need to put it into `/root/.bashrc` too.

**Comment by Apollon77** [comment]
Sounds hacky, but I think we have no other way :-(
