### ISSUE TITLE
Feature request: Ability to add file path to existing SSL certificates

### ISSUE THREAD

**Issue by agentclark** [ioBroker/ioBroker#22]
It would be nice to point ioBroker to existing certificates. The Lets Encrypt option is great but I already have a service for auto-renewal and I use the certificates for various other services.

**Comment by GermanBluefox** [comment]
I think it is useful Feature. 
Additionally, I think, that poll interval must be defined. Because not all OS can use "watch". And it could last some minutes, till new certificates will be used.

**Comment by agentclark** [comment]
any news on this enhancement?
thanks!

**Comment by GermanBluefox** [comment]
In the next version of js-controller and admin.

**Comment by GermanBluefox** [comment]
If you update js-controller and admin from git, it should work

**Comment by agentclark** [comment]
I think I already got the latest versions (admin: 2.0.2, js-controller: 1.1.3) but I don't see anything. I can point to a local certificate but not to a certificate on the host. Am I missing something?
Thank you!

**Comment by GermanBluefox** [comment]
I pushed today js-controller and admin, if you want you can pull it from
github and test, elsewise just wait the official way. (In one month)

2017-08-19 11:41 GMT+02:00 agentclark <notifications@github.com>:

**Comment by GermanBluefox** [comment]
This must work now

**Comment by agentclark** [comment]
Do I have to go via Lets Encrypt in options or is there another way I'm missing?
And if so, is it sufficient to only point to the existing certificates or do I have to add mail and domains?
Thank you!

Admin is at 2.0.7 and js-controller at 1.2.0

**Comment by agentclark** [comment]
Thank you!

**Comment by ggraziotti** [comment]
Only point to path certificate directory or domainname.crt file ?
I have also root, fuul-chain and intermediate .crt flies ?
Where I have to put private key ?
