### ISSUE TITLE
problem with iobroker installation

### ISSUE THREAD

**Issue by experiencingiot** [ioBroker/ioBroker#223]
I'm not getting the installation method for windows. I have already installed iobroker and webservice automatically starts at 8081 at the end. However, when I need to access that local host again later, i just can't. I'm not understanding the problem.
Maybe some command can help in the console but i'm not sure which command to use.

**Comment by Apollon77** [comment]
How you installed it? With the windows installer? Which version? Did you read forum
About it.

**Comment by experiencingiot** [comment]
Yes, with windows installer. I read through the forum but I think no
problem refers to this.
Node.js version 10.16.3

**Comment by Apollon77** [comment]
Then please write in the forum thread for windows installer first.
