### ISSUE TITLE
iCal Datenpunkt für Termine von Gestern

### ISSUE THREAD

**Issue by StM47** [ioBroker/ioBroker#225]
Hi,
ist es möglich, dem Adapter iCal einen Datenpunkt für Termine von gestern hinzuzufügen,
so dass man einen Termin in der Vergangenheit triggern kann.
Hintergrund: Ich bin Schichtarbeiter und steuere meien Heizung im Schlafzimmer in ioBroker mit iCal und Blockly. Das heißt, wenn ich Nachtschicht habe, läuft die Heizung anders, als bei Tagschicht, damit ich in Ruhe schlafen kann. Die Nachtschichten werden über den iCal Adapter abgefragt. Problem ist, dass nach der letzten Nachtschicht nichts mehr im Kalender steht und die Heizung mit Tagschicht heizt und ich nicht schlafen kann.

**Comment by AlCalzone** [comment]
Issue bitte im Repo für den iCal-Adapter erstellen!
https://github.com/iobroker-community-adapters/ioBroker.ical
