### ISSUE TITLE
Is there a recommended way to develop an adapter with its own API

### ISSUE THREAD

**Issue by norman-knott** [ioBroker/ioBroker#234]
Hi there!
I see there are adapters that provide an API. But I don't find information about how to provide an adapter specific API for external applications. For example a REST API.

TBH I don't know anything about Node.js and ioBroker development. Just started with a generated adapter template.

**Comment by AlCalzone** [comment]
To provide external APIs, you need some kind of server. This can be a HTTP(s) server, which is most easily done with [express](https://www.npmjs.com/package/express) or more low-level (TCP/UDP) using [sockets](https://nodejs.org/api/dgram.html).

**Comment by Apollon77** [comment]
In fact check adapter code from simple-api or swagger or geofency. In fact you have two choices:
* build them as "web extension", so they do not need to offer an own server but will be served by the "web" adapter instances under a adapter path. All Requests will then be forwarded
* open an own server using express or what ever technicque you like ...

But in fact you need to get familiar with nodejs for this ;-)

**Comment by norman-knott** [comment]
@AlCalzone @Apollon77 Thanks for your responses.

@Apollon77 I guess you mean extensions for this adapter https://github.com/ioBroker/ioBroker.web . Unfortunately I could not find any documentation. And the API I want to implement, seems to force the usage of `http://{host}:{port}/api`. What might confuse If I add it to the main adapter/application. Because it is not the API of the main application.
So I will go with an own HTTP server in my adapter for now. I guess for my first adapter it's better to how run it in its own process anyway. ^^

**Comment by GermanBluefox** [comment]
> @AlCalzone @Apollon77 Thanks for your responses.
> 
> @Apollon77 I guess you mean extensions for this adapter https://github.com/ioBroker/ioBroker.web . Unfortunately I could not find any documentation. And the API I want to implement, seems to force the usage of `http://{host}:{port}/api`. What might confuse If I add it to the main adapter/application. Because it is not the API of the main application.
> So I will go with an own HTTP server in my adapter for now. I guess for my first adapter it's better to how run it in its own process anyway. ^^

Do you want to add your api to running "web" adapter?
