### ISSUE TITLE
iobroker stürzt nach update direkt nach dem start ab

### ISSUE THREAD

**Issue by Marci112** [ioBroker/ioBroker#238]
ab heute alle offenen updates für den iobroker gemacht unter anderem nodejs. jetzt stürzt es jedesmal ab wenn man es startet. bei absturz komt dieser eintag im log
![iobroker log](https://user-images.githubusercontent.com/59320212/71549548-8da34000-29bf-11ea-800d-15618e778e5a.png)

**Comment by Apollon77** [comment]
Bitte im Forum einen Thread eröffnen mit vollem Log vom Start. Welche Version vom js-controler ist genutzt? Bitte auch dort hinzufügen
