### ISSUE TITLE
Toggling states using MQTT adapter on Iobroker

### ISSUE THREAD

**Issue by experiencingiot** [ioBroker/ioBroker#247]
Hello,,

I'm new working with all this and wondering on some working mechanism.
I'm using zigbee2mqtt on my raspberrypi and a MQTT client on iobroker which receives all possible data in JSON format from my Hue philips devices.
My question was that how can I automate my devices back using Iobroker (same adapter) as already present as a builtin functionality in HUE philips adapter. 

Any ideas would be appreciated.

**Comment by Apollon77** [comment]
I think best open a thread in our forum to discuss your usage scenario in detail. We mainly use GitHub for isues and for discussions Forum is better place :-)
