### ISSUE TITLE
smartmeter URL problem

### ISSUE THREAD

**Issue by HeiLuRa** [ioBroker/ioBroker#249]
Hallo apollo77,
ich hoffe, ich habe Dich richtig verstanden.
[smartmeter-problem_DEBUG-Mode.txt](https://github.com/ioBroker/ioBroker/files/4143863/smartmeter-problem_DEBUG-Mode.txt)

**Comment by Apollon77** [comment]
Ne bitte im Apollon77/iobroker.smartmeter Repo das issue anlegen. Und mit Link ins Forum zu den Details oder hier dazu. Ich hab viel um die Ohren - nur ein log sagt mir in ner Woche nix mehr.
