### ISSUE TITLE
CLI command visdebug does change the cache.manifest file only once

### ISSUE THREAD

**Issue by armintan** [ioBroker/ioBroker#250]
The visdebug icli command implementation reads the cache.manifest file from the iobroker.vis adapter directory (in node_modules), changes a number by incrementing it, and updates the cache.manifest file in the iobroker-data/files/vis directory. So the source is not changed and therefore the increment happens only the first time. 

Also, index.html.original an edit.html.original do not exist and hence are not copied. I do not know if this is an issue, but I saw it in some forums, that this step is required.

**Comment by Apollon77** [comment]
Can you please create this issue in the iobroker.vis repo if it belongs to vis? Thank you

**Comment by armintan** [comment]
Certainly I can do this, but even when the corresponding code is in the iobroker.js-controller package in the lib/setup/setupVisDebug.js file?

**Comment by Apollon77** [comment]
yes then you are right and it needs to go into js.controlelr :-)
