### ISSUE TITLE
Increase Timeout time for hostinfo please

### ISSUE THREAD

**Issue by nob0dy80** [ioBroker/ioBroker#253]
Hello,

i'm using iobroker in a multihost enviroment.
One of the host is a slow Raspberry Zero W which is handling only the Zigbee adapter (fast enough for that)
Since the Raspi Zero isnt the fastest device, the log shows multiple timeouts like this:

host.iobrokerslave | 2020-02-15 20:22:55.386 | error | cannot get getHostInfo: timeout
-- | -- | -- | --
host.iobrokerslave | 2020-02-15 20:05:53.112 | error | cannot get getHostInfo: timeout
host.iobrokerslave | 2020-02-15 19:51:46.465 | error | cannot get getHostInfo: timeout
host.iobrokerslave | 2020-02-15 19:51:46.260 | error | cannot get getHostInfo: timeout
host.iobrokerslave | 2020-02-15 18:05:41.304 | error | cannot get getHostInfo: timeout
host.iobrokerslave | 2020-02-15 17:44:03.807 | error | cannot get getHostInfo: timeout

Is there a way to increase the timout time for the host detection?

Kind regards

**Comment by Apollon77** [comment]
Please create the issue in js-Controller repository.
