### ISSUE TITLE
No NPM Version in Hostinfo on armv6l

### ISSUE THREAD

**Issue by nob0dy80** [ioBroker/ioBroker#254]
If you use a raspberry 1 or a raspberry zero, which expects a armv6l version of Nodejs and NPM, which has to be installed manually cause its not supported by the "curl -sL https://deb.nodesource.com/setup_x.x | sudo -E bash -"-command, the npm version on the hostinfo is not displayed:

![image](https://user-images.githubusercontent.com/28686079/74594041-12aaed00-5032-11ea-9c67-0fc88cae3518.png)
![image](https://user-images.githubusercontent.com/28686079/74594198-ae892880-5033-11ea-9130-062a74e30a2a.png)

**Comment by Apollon77** [comment]
Please create this issue in js-controller repository. Thank you.
