### ISSUE TITLE
using ram on synology docker

### ISSUE THREAD

**Issue by maestroat** [ioBroker/ioBroker#256]
Datenträger verfügbar: 25.4 %, gesamte RAM-Nutzung: 438 MB / Frei: 2% = 285 MB [Host: iobroker - 9 Prozesse]

i have 16GB first start it is okay but when reboot system i see this? why docker not use more freee mb? 2% is not much, synology have more than 8-10GB Free to use

**Comment by buanet** [comment]
A Docker container is NOT a virtual machine! It only uses as mutch RAM as it needs. If you want to limit the usage. Read here: https://docs.docker.com/config/containers/resource_constraints/

Reserving RAM is not needed.

BTW, I think this is not an issue and I would vote for closing it.

Regards,
André
