### ISSUE TITLE
update, upgrade from different Active repository

### ISSUE THREAD

**Issue by EvilEls** [ioBroker/ioBroker#26]
It appears that 
`iobroker update` uses the `Active repo` which can be identified by `iobroker repo`.

`iobroker upgrade` seems to not care about `Active repo`. It uses the local repo `conf/sources-dist.json`.

**Comment by Apollon77** [comment]
Which js-controller version is installed?
The upcoming 1.1.4 will have a fix for this already. Available on GitHub

**Comment by EvilEls** [comment]
`installed 1.1.3`
Good to know! Thx!
