### ISSUE TITLE
homematic ccu adress not on Port 80 

### ISSUE THREAD

**Issue by arto5754** [ioBroker/ioBroker#265]
**HomeMatic CCU address:** Here the IP address of the CCU is selected from a pulldown menu, the data of which should be transferred to ioBroker. The available IP addresses correspond to the hm-rpc adapters configured so far.
If the HomeMatic CCU address does not have the **standard http port 80**, e.g. Port 90, the CCU is not reached by hm-rega.

Reason for another port of the CCU:
If Iobroker, WebMatic, Alexa is running on one computer, port 80 must be forwarded to another port, otherwise Amazon Echo Hub will not work under node-red.

**Comment by Apollon77** [comment]
please create issue on relevant adapter repository
