### ISSUE TITLE
Adapter page - Filter - always click twice

### ISSUE THREAD

**Issue by Seqway** [ioBroker/ioBroker#266]
Hello,
i am running iobroker with
Node.js v10.19.0
js-controller 2.2.9

and i have ti click always 2 times on the Adapter page under Filter to write something in !

I have another (test)System running with
Node.js v12.16.2
js-controller 3.0.14
with the same behaviour. Please check !

**Comment by Apollon77** [comment]
Can you please open that issue in iobroker.admin repository?! Thank you.
