### ISSUE TITLE
Iobroker google mini /hub

### ISSUE THREAD

**Issue by Emphantom4d** [ioBroker/ioBroker#269]
Hey.  began to study iobroker.  but so few lessons on creating paths.  where to click how to do.  many questions .  I decided to make friends google nest hub in the material ui driver.  I succeeded, but not all.  I click everything and see if it works or not.  not quite convenient.  if anyone succeeded write.  as well as problems with node.js, I have v10.17.0 and js-controller 2.1.0 and don’t install a new one, as soon as I want to install, I have problems with Windows services (I have windows 10).  very few lessons.  or I don’t know where to look.  I don’t know how to write codes, but not everyone can.

to connect google nest hub ... you need to specify the ROLE in OBJECTS: media.track, and in the functions specify audio / music

in the materials you can see what you are watching or listening to, you can stop either the previous track or stop.  but time cannot be moved.

maybe there are options for something else to do?

**Comment by Apollon77** [comment]
I think it is best to come into our Forum (https://forum.iobroker.net) and get support there
