### ISSUE TITLE
ioBroker running but no Web UI

### ISSUE THREAD

**Issue by maximinus333** [ioBroker/ioBroker#276]
On a RaspberryPi 4 Iset up a virgin system using ioBroker image. As in previous installations I was not sucsessful installing Mosquitto I used Scargill`s The Script installing Node-Red and Mosquitto. Everything went as expected but ioBroker was not accessible any more on:8081. Reinstalled it using der curl Script but no change. iobroker list instances gives following message:
As I am new in Linux I cannot understand. May please have someone have a look into this to solve my problem:
Best regards
pi@raspberrypi-ioB:/opt/iobroker $ iobroker list instances
(node:1289) UnhandledPromiseRejectionWarning: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:190:15)
    at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:304:14)
(node:1289) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1289) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  system.adapter.admin.0                 : admin                 -  enabled, port: 8081, bind: 0.0.0.0, run as: admin
  system.adapter.discovery.0             : discovery             -  enabled
  system.adapter.info.0                  : info                  -  enabled

+ instance is alive
pi@raspberrypi-ioB:/opt/iobroker $
-bash: pi@raspberrypi-ioB:/opt/iobroker: Datei oder Verzeichnis nicht gefunden
pi@raspberrypi-ioB:/opt/iobroker $ (node:1289) UnhandledPromiseRejectionWarning: ParserError: Protocol error, got "H" as reply type byte. Please report this.
-bash: Syntaxfehler beim unerwarteten Wort `UnhandledPromiseRejectionWarning:'
pi@raspberrypi-ioB:/opt/iobroker $     at handleError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:190:15)
-bash: Syntaxfehler beim unerwarteten Wort `('
pi@raspberrypi-ioB:/opt/iobroker $     at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:304:14)
-bash: Syntaxfehler beim unerwarteten Wort `('
pi@raspberrypi-ioB:/opt/iobroker $ (node:1289) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
-bash: Syntaxfehler beim unerwarteten Wort `UnhandledPromiseRejectionWarning:'
pi@raspberrypi-ioB:/opt/iobroker $ (node:1289) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
-bash: Syntaxfehler beim unerwarteten Wort `[DEP0018]'
pi@raspberrypi-ioB:/opt/iobroker $   system.adapter.admin.0                 : admin                 -  enabled, port: 8081, bind: 0.0.0.0, run as: admin
-bash: system.adapter.admin.0: Kommando nicht gefunden.
pi@raspberrypi-ioB:/opt/iobroker $   system.adapter.discovery.0             : discovery             -  enabled
-bash: system.adapter.discovery.0: Kommando nicht gefunden.
pi@raspberrypi-ioB:/opt/iobroker $   system.adapter.info.0                  : info                  -  enabled
-bash: system.adapter.info.0: Kommando nicht gefunden.
pi@raspberrypi-ioB:/opt/iobroker $
pi@raspberrypi-ioB:/opt/iobroker $ + instance is alive
-bash: +: Kommando nicht gefunden.
pi@raspberrypi-ioB:/opt/iobroker $ pi@raspberrypi-ioB:/opt/iobroker $
-bash: pi@raspberrypi-ioB:/opt/iobroker: Datei oder Verzeichnis nicht gefunden
pi@raspberrypi-ioB:/opt/iobroker $

**Comment by Apollon77** [comment]
Do the problem still exist?
