### ISSUE TITLE
flot improve handling

### ISSUE THREAD

**Issue by Hardwarefreak** [ioBroker/ioBroker#286]
Hallo,
ist es möglich bez. machbar die Presets z.B. in der Form:

h t t p://127.0.0.1:8082/flot/preset.html?Spritpreise

aufzurufen

anstatt einem exterm langen Seitenaufruf, z.B.:

h t t p://127.0.0.1:8082/flot/index.html?l%5B0%5D%5Bid%5D=hm-rega.0.18106&l%5B0%5D%5Binstance%5D=sql.0&…. titleSize=16&legend=sw&legColumns=3 … u.s.w. "

**Comment by Apollon77** [comment]
Presets in flot are in since 1.10 ... see https://github.com/ioBroker/ioBroker.flot
