### ISSUE TITLE
Problem when I try upgrade lastest version iobroker

### ISSUE THREAD

**Issue by cardco** [ioBroker/ioBroker#287]
$ ./iobroker upgrade
Update repository "latest" under "http://download.iobroker.net/sources-dist-latest.json"
ERROR: Cannot download json from http://download.iobroker.net/sources-dist-latest-hash.json. Error: Error: ETIMEDOUT
failed to download new sources, use cached sources
ERROR: Cannot download json from http://download.iobroker.net/sources-dist-latest.json. Error: Error: ETIMEDOUT
ERROR: (node:729) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'indexOf' of undefined    at Upgrade.upgradeAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpgrade.js:198:21)    at Upgrade.upgradeAdapterHelper (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpgrade.js:50:14)    at /opt/iobroker/node_modules/iobroker.js-controller/lib/setup.js:732:37    at /opt/iobroker/node_modules/iobroker.js-controller/lib/setup.js:2325:96    at /opt/iobroker/node_modules/iobroker.objects-redis/index.js:1:109341    at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)    at /opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49    at processTicksAndRejections (internal/process/task_queues.js:97:5)
ERROR: (node:729) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)(node:729) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by thost96** [comment]
Please make sure you can access http://download.iobroker.net/sources-dist-latest.json using wget or any other tool. The error message only says, that iobroker couldn't get the file http://download.iobroker.net/sources-dist-latest.json to check for updated versions and there were some webserver difficulties yesterday, so please have another try.

**Comment by Apollon77** [comment]
Additionall:
* iobroker update -> reloads repository
* iobroker upgrade self -> update controller!
