### ISSUE TITLE
Please fix spelling and grammar

### ISSUE THREAD

**Issue by jhedtmann** [ioBroker/ioBroker#289]
I know, English is not the native language of many of the contributors to ioBroker. But given of all the bad language around, please try to fix the wording and the grammar of ioBroker documentation. Many issues are not even specific to English, e.g. the plural of 'status' is 'status' (with a long 'u'), not 'statuses', nor 'statusses', nor 'stati', in all languages that use this Latin word.

leo.org can help, so can I, if needed.

And yes, I make mistakes, too...

Keep up the excellent work!

Jörg

**Comment by Apollon77** [comment]
Feel free to provide PRs for the respective documentation’s you mean.
