### ISSUE TITLE
iframe not working

### ISSUE THREAD

**Issue by downspath** [ioBroker/ioBroker#291]
Hello,

i have iobroker on a raspberry. I am trying to make one page with iframes to all my important tools (webmin, phpmyadmin, iobroker ...)  But i have trouble getting iobroker to run. it is blocking the connection if run from an iframe. the link within the iframe works if i type it into the browser.

(the code is fine) 
            <iframe style="width:100%;height:100%;" frameBorder="0" src="https://XXXXX.XXX:8081/"></iframe>

PS: if i try to run VIS within an iframe it works fine. its only the admin one (port 8081) that doesnt work.

**Comment by Apollon77** [comment]
Then please open the issue with admin project in GitHub and check the browser console for errors. Maybe cors is the reason?!
