### ISSUE TITLE
Request Darkmode for ioBroker

### ISSUE THREAD

**Issue by FlexerJR** [ioBroker/ioBroker#293]
Hello dear Devs, 
I request the Darkmode for ioBroker. There is nothing more to say ;)

Thank you.

**Comment by DutchmanNL** [comment]
@Apollon77 @GermanBluefox would be interesting for ew admin ?

**Comment by Apollon77** [comment]
Yes Admin issue please

**Comment by DutchmanNL** [comment]
https://github.com/ioBroker/ioBroker.admin/issues/620
