### ISSUE TITLE
Iobroker nach Stromausfall tot

### ISSUE THREAD

**Issue by Semesch** [ioBroker/ioBroker#294]
Hallo, ich komme leider nicht mehr weiter, mir fehlt hier einfach das Know-how.
Nach einem Stromausfall startet iobroker nicht mehr. Homematic startet problemlos. Ich bekomme auch keinen Zugriff mehr auf Iobroker per SSH.
In der fritzbox finde ich aber beide IP-Adressen als online.
Verwende die pivccu. Und Alex Reinert hat gedacht ich bin hier gut aufgehoben.
Bitte helft mir.

**Comment by Apollon77** [comment]
Am besten aufgehoben bist Du denke ich im Forum.

die erste Farge ist ja was mit dem System los ist. "Nach stromausfall" klingt danach das ggf das Dateisystem von deinem Host defekt ist weil der Strom halt "im falschen Zeitpunkt" ausgegangen ist. Also am besten Monitor anschliessen und schauen was beim Boot kommt. Das klingt eher nicht danach das es der ioBroker ist sondern eher dein host - weil wenn du per SSH nicht drauf kommst stimmt was anderes nicht
