### ISSUE TITLE
HMIP BROll  % Level is not 100%(101%)

### ISSUE THREAD

**Issue by pclars** [ioBroker/ioBroker#295]
The Level is not correct in IoBroker, 100% is 101%  90%is 91%

the Problem is when i use the Voice Command to Alexa..   i Say ,,Alexa Rollladen Wohnzimmer 100%`` the Broll controlls down...
when i say ,,Alexa Rolladen Wohnzimmer 99%´´ it was 100% level...

The level configuration was not right... see Screenshot
![Screenshot_2020-10-17 objects - ioBroker](https://user-images.githubusercontent.com/67156995/96334466-4fbbf900-1071-11eb-8098-fcccf95cabe2.png)

**Comment by AlCalzone** [comment]
@Apollon77 @GermanBluefox transfer issue to hm-rpc repo?

**Comment by Apollon77** [comment]
@foxriver76 ?!

**Comment by foxriver76** [comment]
can be closed
