### ISSUE TITLE
Error bei der Installation und Upgrade von allen Adaptern

### ISSUE THREAD

**Issue by Peter1980FFM** [ioBroker/ioBroker#296]
Hallo zeit Kurzem bekomme ich bei jedem Update oder Neu Installation diese Fehlermeldungen..
node-aead-crypto not needed on this system, since all ciphers are natively supported
In file included from ../authenticate_pam.cc:23:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2294:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
../authenticate_pam.cc: In function ‘void after_doing_auth(uv_work_t*, int)’:
../authenticate_pam.cc:107:87: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), Nan::New(m->callback), 1, args);
                                                                                       ^
In file included from ../authenticate_pam.cc:23:
../../nan/nan.h:1026:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
../authenticate_pam.cc:107:87: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), Nan::New(m->callback), 1, args);
                                                                                       ^
In file included from ../authenticate_pam.cc:23:
../../nan/nan.h:1026:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
../authenticate_pam.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE Authenticate(Nan::NAN_METHOD_ARGS_TYPE)’:
../authenticate_pam.cc:147:83: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   Local<Value> res = options->Get(Nan::New<String>("serviceName").ToLocalChecked());
                                                                                   ^
In file included from /home/iobroker/.cache/node-gyp/12.19.0/include/node/v8-internal.h:14,
                 from /home/iobroker/.cache/node-gyp/12.19.0/include/node/v8.h:27,
                 from /home/iobroker/.cache/node-gyp/12.19.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../authenticate_pam.cc:23:
/home/iobroker/.cache/node-gyp/12.19.0/include/node/v8.h:3553:51: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
                                                   ^~~
/home/iobroker/.cache/node-gyp/12.19.0/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../authenticate_pam.cc:150:69: error: no matching function for call to ‘v8::String::WriteUtf8(char [128], unsigned int)’
    serviceName->WriteUtf8(m->serviceName, sizeof(m->serviceName) - 1);
                                                                     ^
In file included from /home/iobroker/.cache/node-gyp/12.19.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../authenticate_pam.cc:23:
/home/iobroker/.cache/node-gyp/12.19.0/include/node/v8.h:2878:7: note: candidate: ‘int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const’
   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
       ^~~~~~~~~
/home/iobroker/.cache/node-gyp/12.19.0/include/node/v8.h:2878:7: note:   no known conversion for argument 1 from ‘char [128]’ to ‘v8::Isolate*’
../authenticate_pam.cc:152:69: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   res = options->Get(Nan::New<String>("remoteHost").ToLocalChecked());
                                                                     ^
In file included from /home/iobroker/.cache/node-gyp/12.19.0/include/node/v8-internal.h:14,
                 from /home/iobroker/.cache/node-gyp/12.19.0/include/node/v8.h:27,
                 from /home/iobroker/.cache/node-gyp/12.19.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../authenticate_pam.cc:23:
/home/iobroker/.cache/node-gyp/12.19.0/include/node/v8.h:3553:51: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
                                                   ^~~
/home/iobroker/.cache/node-gyp/12.19.0/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../authenticate_pam.cc:155:66: error: no matching function for call to ‘v8::String::WriteUtf8(char [128], unsigned int)’
    remoteHost->WriteUtf8(m->remoteHost, sizeof(m->remoteHost) - 1);
                                                                  ^
In file included from /home/iobroker/.cache/node-gyp/12.19.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../authenticate_pam.cc:23:
/home/iobroker/.cache/node-gyp/12.19.0/include/node/v8.h:2878:7: note: candidate: ‘int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const’
   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
       ^~~~~~~~~
/home/iobroker/.cache/node-gyp/12.19.0/include/node/v8.h:2878:7: note:   no known conversion for argument 1 from ‘char [128]’ to ‘v8::Isolate*’
../authenticate_pam.cc:160:58: error: no matching function for call to ‘v8::String::WriteUtf8(char [128], unsigned int)’
  username->WriteUtf8(m->username, sizeof(m->username) - 1);
                                                          ^
In file included from /home/iobroker/.cache/node-gyp/12.19.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../authenticate_pam.cc:23:
/home/iobroker/.cache/node-gyp/12.19.0/include/node/v8.h:2878:7: note: candidate: ‘int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const’
   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
       ^~~~~~~~~
/home/iobroker/.cache/node-gyp/12.19.0/include/node/v8.h:2878:7: note:   no known conversion for argument 1 from ‘char [128]’ to ‘v8::Isolate*’
../authenticate_pam.cc:161:58: error: no matching function for call to ‘v8::String::WriteUtf8(char [128], unsigned int)’
  password->WriteUtf8(m->password, sizeof(m->password) - 1);
                                                          ^
In file included from /home/iobroker/.cache/node-gyp/12.19.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../authenticate_pam.cc:23:
/home/iobroker/.cache/node-gyp/12.19.0/include/node/v8.h:2878:7: note: candidate: ‘int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const’
   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
       ^~~~~~~~~
/home/iobroker/.cache/node-gyp/12.19.0/include/node/v8.h:2878:7: note:   no known conversion for argument 1 from ‘char [128]’ to ‘v8::Isolate*’
../authenticate_pam.cc: At global scope:
../authenticate_pam.cc:170:11: error: variable or field ‘init’ declared void
 void init(Handle<Object> exports) {
           ^~~~~~
../authenticate_pam.cc:170:11: error: ‘Handle’ was not declared in this scope
../authenticate_pam.cc:170:11: note: suggested alternative: ‘rand_r’
 void init(Handle<Object> exports) {
           ^~~~~~
           rand_r
../authenticate_pam.cc:170:24: error: expected primary-expression before ‘>’ token
 void init(Handle<Object> exports) {
                        ^
../authenticate_pam.cc:170:26: error: ‘exports’ was not declared in this scope
 void init(Handle<Object> exports) {
                          ^~~~~~~
In file included from ../../nan/nan.h:56,
                 from ../authenticate_pam.cc:23:
../authenticate_pam.cc:175:31: error: ‘init’ was not declared in this scope
 NODE_MODULE(authenticate_pam, init);
                               ^~~~
/home/iobroker/.cache/node-gyp/12.19.0/include/node/node.h:727:36: note: in definition of macro ‘NODE_MODULE_X’
       (node::addon_register_func) (regfunc),                          \
                                    ^~~~~~~
../authenticate_pam.cc:175:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(authenticate_pam, init);
 ^~~~~~~~~~~
../authenticate_pam.cc:175:31: note: suggested alternative: ‘int’
 NODE_MODULE(authenticate_pam, init);
                               ^~~~
/home/iobroker/.cache/node-gyp/12.19.0/include/node/node.h:727:36: note: in definition of macro ‘NODE_MODULE_X’
       (node::addon_register_func) (regfunc),                          \
                                    ^~~~~~~
../authenticate_pam.cc:175:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(authenticate_pam, init);
 ^~~~~~~~~~~
make: *** [authenticate_pam.target.mk:109: Release/obj.target/authenticate_pam/authenticate_pam.o] Fehler 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.51-v7l+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/authenticate-pam
gyp ERR! node -v v12.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

Was ist zu tun?

**Comment by Apollon77** [comment]
It seems that not all relevant linux packages are installed OR the authenticate-pam lib is not fully comoatible with your nodejs version. Normally this is an optional dependenc only so just ignore these warnings
