### ISSUE TITLE
Adapter updates on a installation with docker container does not work

### ISSUE THREAD

**Issue by nkleber78** [ioBroker/ioBroker#298]
I have serious problems with my installation inside a docker container. The main problem is, that on every update of a adapter, the rest of the installation is destroyed in a way that the adapters continuous needs reinstalling. See one sample in screenshot. To get the system running stable the only way is to execute the reinstall.js script, but then all the adapters are again on the previous version. 
<img width="1021" alt="Screenshot 2020-11-19 at 23 57 05" src="https://user-images.githubusercontent.com/35381530/99734355-fb1dfa80-2ac2-11eb-9c0f-3674c8acf5da.png">

Is there any idea what could cause such behaviour and how to solve this?

here a complete log of the reinstall.js log created [2020-11-19T23_36_15_330Z-debug.log](https://github.com/ioBroker/ioBroker.docs/files/5570331/2020-11-19T23_36_15_330Z-debug.log)
I have following docker container as base https://registry.hub.docker.com/r/buanet/iobroker

**Comment by Apollon77** [comment]
Plese post the issue in the docker container and verify that not a usage topic is the reason. The npm log shows something strange with your iobation node_modules directory
