### ISSUE TITLE
Adapterliste lädt nicht mehr

### ISSUE THREAD

**Issue by D4rkF4ce** [ioBroker/ioBroker#30]
Hallo,

bis gestern lief alles noch ohne Probleme. Seit einem Klick auf "Adapter Informationen aktualisieren" wird die Adapterliste nicht mehr angezeigt. Über F12 im Chrome wird mir ein Fehler angezeigt.
![iobroker_error](https://user-images.githubusercontent.com/8313770/34561718-a87def00-f14b-11e7-838a-ecc6d94a283f.PNG)

Hat noch jemand das selbe Problem?
Internet funkt
Iobroker läuft auf einem Raspi3
OS ist up to date

Danke & LG
Dark!

**Comment by DutchmanNL** [comment]
dazugehoeriger thread im Forum: http://forum.iobroker.net/viewtopic.php?f=22&t=10302

**Comment by D4rkF4ce** [comment]
Hallo 

Danke für die schnelle Antwort. Wie ich sehe ist das Problem bekannt nur ist der letzte Post knapp 1 Jahr alt.. Liegt es jetzt am Repo Server oder an meiner Installation? 
Hat der JS Fehler etwas damit zu tun?
Viel weiter hilft mir das nämlich nicht.
Lese hier nur warten heraus.

LG
Dark!

**Comment by DutchmanNL** [comment]
Hi Dark,

Es liegt an der repro und wird gerade im hintergrund durch die admins gefixed sollte heut abend wieder gehen

**Comment by D4rkF4ce** [comment]
Hallo

Ok danke für die Info und ich warte Mal ab.
Ansonsten läuft ja ee alles.

Danke & LG,
Dark!

**Comment by DutchmanNL** [comment]
das problem sollte jetzt behoben sein bitte probieren

**Comment by GermanBluefox** [comment]
Und closen...

2018-01-04 17:06 GMT+01:00 Dutchman <notifications@github.com>:

**Comment by D4rkF4ce** [comment]
Hallo also bei mir tut sich noch nichts. Muss ich etwas updaten, neustarten oder der Gleichen?

Danke & LG,
Dark!

**Comment by D4rkF4ce** [comment]
Heho,

nachdem Cache leeren nichts geholfen hat. Alle Browser weiterhin eine leere Liste angezeigt haben, habe ich über Putty direkt die Adapterliste aufgerufen bzw upgedated "sudo iobroker update" nun wird die Liste wieder in jedem Browser angezeigt. JS Fehler ist auch weg.

Vielen Danke für euer Feedback!
LG,
Dark!

**Comment by robdg80** [comment]
Es gibt eine Fehleranalyse:
http://forum.iobroker.net/viewtopic.php?p=110633#p110608

Es liegt daran, das einige Adapter den titel geäönder haben:
"title": {
          "en": "Flot Charts",
          "de": "Flot-Diagrammen",
          "ru": "Графики c Flot",
          "pt": "Flot Charts",
          "nl": "Flot charts",
          "fr": "Graphiques des Flot",
          "it": "Grafici Flot",
          "es": "Gráficos de Flot",
          "pl": "Wykresy Flot"
        }

"Das versteht adminAdapter.js (in Zeile 665) nicht!"

**Comment by GermanBluefox** [comment]
Please update chromecast to 1.4.1 and flot to 1.7.4 and update repository to fix this issue.
