### ISSUE TITLE
Rechtefrage zum Lesen einer Datei auf einem Server in einem Adapter

### ISSUE THREAD

**Issue by pingsps** [ioBroker/ioBroker#300]
Hallo Linuxfans,
ich bin jetzt nicht der Linuxguru, deshalb bin ich bisher an der Frage gescheitert.
Also ich möchte im Trashadapter aus dem iobroker einen Kalender auf dem server lesen. Im Log sehe ich aber, dass die Datei nicht gelesen werden kann. Jetzt frage ich mich natürlich warum?

Also habe ich das Terminal im iobroker geöffnet und hier ein paar Befehle reingetippt. Natürlich habe ich vorher kontrolliert, ob ich Rechte auf dem Server habe. Der iobroker ist hier leseberechtigt. (Ich nehme an, Schreibrechte braucht er dazu nicht. 
Also Kommandozeiles: ls //192.168.0.20 --> geht nicht: ls: Zugriff auf '//192.168.0.20' nicht möglich
: Datei oder Verzeichnis nicht gefunden
/opt/iobroker$ ls //192.168.0.20/.
Über den Windows PC kann ich aber auf den Server zugreifen, kann die Datei lesen...

Damit brauche ich mit dem Trashadapter nicht weiter machen. Habe aber alles mögliche probiert, überall der gleiche Fehler.

Die Linuxgurus werden sich natürlich schief lachen, aber ich komme leider nicht weiter. Kann mit jemand einen tipp geben. Danke schon mal im Voraus :-)

**Comment by Apollon77** [comment]
Puuhh ... das ist kein okaler Pfad. Wenn musst Du das mounten wenn es ein entfernter Host ist. Aber am besten mal im Forum fragen!
