### ISSUE TITLE
New User + admin = permissionError // Please help!

### ISSUE THREAD

**Issue by bauerpower69** [ioBroker/ioBroker#307]
Dear all,

I have no idea what to do anymore .. 
I have created a **new user**!
I add the account into admin group and it seems the user is not able to 
change objects ....

e.g. in the Yahka adapter I get the following message: 

![](https://forum.iobroker.net/assets/uploads/files/1607707133823-b48bbc84-5ea7-4dd1-909c-1a9e05ba31e8-image.png)

With the admin account all works fine :-) 

All right's are are checked:

![](https://forum.iobroker.net/assets/uploads/files/1607707218781-7bdfdea0-c0f4-45da-a377-c91793da5431-image.png)

Thank you for help!

Best regards
Joerg

**Comment by Apollon77** [comment]
Please try one thing: Add a new group and give also all rights as Admin ... assign user to this. is it then working?

**Comment by bauerpower69** [comment]
Dear Ingo,

I appreciate your fast reply. 

As you mentioned I create a new Group (Manager) and assign all rights to this new group.
I assign the user (Jan) to this group and removed as well the Admin assignment.

![image](https://user-images.githubusercontent.com/25681982/102695784-cf10a900-4229-11eb-9f4d-41ded8091913.png)

![image](https://user-images.githubusercontent.com/25681982/102695769-b4d6cb00-4229-11eb-9519-a97c94ea5db3.png)

Unfortunately the same situation:

Create **datapoint:**
![image](https://user-images.githubusercontent.com/25681982/102695808-f8313980-4229-11eb-80b9-0ac2726ba9db.png)

**Changes in adapter:**
![image](https://user-images.githubusercontent.com/25681982/102695819-08e1af80-422a-11eb-8892-33fdf2578b5e.png)

I made test... usually I use the ADMIN account to work, so I created a new user, add to ADMIN Group, logged in,
all tests positive! (????)

I deleted "Jan", created new user "Jan", assign to Admin.... **FAILED**
![image](https://user-images.githubusercontent.com/25681982/102696103-2748aa80-422c-11eb-974b-1f488f9fab46.png)

SCARRY 

Please let me know if you need further tests :-)

Danke!


Jörg

**Comment by Apollon77** [comment]
How the affected object is looking?

**Comment by bauerpower69** [comment]
Dear Ingo,

I guess you mean last image "Fehler Zugriffsfehler"? 
I tried to add a Datapoint with the new created profile.

**Profile:**
![image](https://user-images.githubusercontent.com/25681982/102871955-5edb7080-443f-11eb-9cc0-d7a60b403dd6.png)

**Create new object**
![image](https://user-images.githubusercontent.com/25681982/102871677-ff7d6080-443e-11eb-82e3-7b8f0d1b26cd.png)

**Here is the result:**
![image](https://user-images.githubusercontent.com/25681982/102871786-26d42d80-443f-11eb-9ee3-904752bc5477.png)


Hope I understood your question right! ;-)

Best regards


Jörg

**Comment by Apollon77** [comment]
And js-controller is a 3.1.6?

**Comment by bauerpower69** [comment]
Dear Ingo,

here are the settings:

Platform: linux
os: linux
Architecture: arm
CPUs: 4
Speed: 1500 MHz
Model: ARMv7 Processor rev 3 (v7l)
RAM: 7.6 GB 
System uptime: 13 T. 02:51:36
Node.js: v12.20.0
NPM: 6.14.8
adapters count: 322
Disk size: 58.3 GiB
Disk free: 50.8 GiB
Uptime: 13 T. 02:51:41
Active instances: 14

Please let me know if you need more information ....

Thanks


Joerg

**Comment by Apollon77** [comment]
Yes, which js-controller version do you use? (Host tab)

**Comment by bauerpower69** [comment]
Dear Info,

I'm using 3.1.6!

![image](https://user-images.githubusercontent.com/25681982/102938622-f3c88300-44ac-11eb-881a-2d6a7546fcf3.png)

Thank you for your support!

Best regards

Joerg

**Comment by Apollon77** [comment]
Please check with current version og Admin and if still not working please check Admin issues
