### ISSUE TITLE
Received text via mqtt not accepted

### ISSUE THREAD

**Issue by Jonny87** [ioBroker/ioBroker#31]
I tried to receive owntracks values via mqtt (cloudmqtt). 

The sent text looks like:

{"_type":"location","tid":"pn","acc":19,"batt":0,"lat":xx.6933686,"lon":x.422188,"t":"u","tst":1515319324}

On data point only "undefined" will be showed. 

If I send an text like:

{"_type":"location","tid":"pn","acc":19,"batt":0,"lat":xx.6933686,"lon":x.422188,"t":"u","tst":1515319324

without curly bracket "}" at the end, then it works.

**Comment by Apollon77** [comment]
Please choose the correct adapter for this issue. The ioBroker repo is only used for initial installation.
