### ISSUE TITLE
iobroker

### ISSUE THREAD

**Issue by Bernstei-Github** [ioBroker/ioBroker#310]

**Comment by thost96** [comment]
Hi @Bernstei-Github,

this issue doesn't contain any information. Was it a mistake or could you please provide more feedback?

**Comment by Bernstei-Github** [comment]
Sorry, I'm new and I posted wrongly

**Comment by thost96** [comment]
Okay, so then you can close this issue down below with your next comment while clicking Close Issue. Thanks!
