### ISSUE TITLE
Add iobroker cli auto completion into installer/fixer

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker#311]
As soon as js.controller 3.2 becomes stable we can also add the autocompletion stuff into installer/fixer, see https://github.com/ioBroker/ioBroker.js-controller/pull/1181

**Comment by AlCalzone** [comment]
@foxriverGo do you have the exact commands that need to happen?

**Comment by Apollon77** [comment]
copy from linked issue

> for most Unix systems, we can now easily create auto-completion, currently, the user could add it to his bashrc via
iobroker _createCompletion >> ~/.bashrc however, we should handle this in the controller or better installer/fixer and should also add the completion for iob and not only iobroker command by adding complete -o default -F _yargs_completions iob too

**Comment by AlCalzone** [comment]
Just appending to .bashrc means we have to check if it was already put in there.
Or does this command `complete -o default -F _yargs_completions iob` take care of everything?

**Comment by foxriver76** [comment]
e.g. 
```
###-begin-iobroker-completions-###
#
# yargs command completion script
#
# Installation: iobroker _createCompletion >> ~/.bashrc
#    or iobroker _createCompletion >> ~/.bash_profile on OSX.
#
_yargs_completions()
{
    local cur_word args type_list

    cur_word="${COMP_WORDS[COMP_CWORD]}"
    args=("${COMP_WORDS[@]}")

    # ask yargs to generate completions.
    type_list=$(iobroker --get-yargs-completions "${args[@]}")

    COMPREPLY=( $(compgen -W "${type_list}" -- ${cur_word}) )

    # if no match was found, fall back to filename completion
    if [ ${#COMPREPLY[@]} -eq 0 ]; then
      COMPREPLY=()
    fi

    return 0
}
complete -o default -F _yargs_completions iobroker
complete -o default -F _yargs_completions iob
###-end-iobroker-completions-###
```

**Comment by AlCalzone** [comment]
Ok so the installer script should find that range in bashrc, remove if necessary and then append it freshly.
I think it already does that for the npm user fix, so it shouldn't be too hard to do.
