### ISSUE TITLE
?

### ISSUE THREAD

**Issue by Qavai** [ioBroker/ioBroker#32]
Скажите, система сейчас проектируется и дальше и будет развиваться?

Стоит ли её применять или есть что-то новое (другое)?

**Comment by maxtox** [comment]
Лучше системы не найдено! Сам искал пол года!

Am 10.01.2018 08:54 schrieb "Eugene Ivanov" <notifications@github.com>:

**Comment by Apollon77** [comment]
check out iobroker.net
