### ISSUE TITLE
ioBroker in Docker: "iobroker stop" needs iobroker user password for sudo

### ISSUE THREAD

**Issue by buanet** [ioBroker/ioBroker#320]
Hi,
just trying to improve my ioBroker-Docker image. During my actual tests, ioBroker wants me to type the iobroker user password (for sudo) when doing a "iobroker stop".  Everything else runs without password. Is that behavior correct?
```
iobroker@develop:/opt/iobroker$ iobroker status
iobroker is not running
iobroker@develop:/opt/iobroker$ iobroker start
Starting iobroker controller daemon...
iobroker controller daemon started. PID: 7845
iobroker@develop:/opt/iobroker$ iobroker restart
Stopping iobroker controller daemon...
iobroker controller daemon stopped.
Starting iobroker controller daemon...
iobroker controller daemon started. PID: 7883
iobroker@develop:/opt/iobroker$ iobroker stop
Stopping iobroker controller daemon...
iobroker controller daemon stopped.
[sudo] password for iobroker:
```
All I did until this point is:
- taking a basic Debian-Docker image
- installing some necessary packages using apt-get
- installing node
- installing iobroker 

Can you please check what's causing this authentication with "iobroker stop"? 

PS: At the moment I do a 
```
echo 'iobroker ALL=(ALL) NOPASSWD: ALL' | EDITOR='tee -a' visudo && echo "iobroker:iobroker" | chpasswd && adduser iobroker sudo
```
in my docker image to give the user "iobroker" sudo rights without password but as this is not the best way I want to completely remove that part.

best regards,
André

**Comment by AlCalzone** [comment]
@buanet would be good to have some input from you so we know how to proceed

**Comment by buanet** [comment]
A lot of things changed until this was opened. I did a quick test. Could not reproduce. 
So this can be closed.
