### ISSUE TITLE
Temperatur Widget blinkt nach Farbänderung per Binding

### ISSUE THREAD

**Issue by freddy-69** [ioBroker/ioBroker#321]
https://forum.iobroker.net/topic/41724/temperatur-widget-blinkt-ungewollt-nach-binding/2?_=1612734815903

Ich hoffe, das reicht so. Alles andere ist unter dem Link im Forum.

Sollte es ein Festure und kein Bug sein, bitte schließen.

Beste Grüße, Steffen

**Comment by Apollon77** [comment]
Wenn es ein problem für vis ist dann bitte im vis projekt das issue anlegen ... oder zu dem Adapter zu dem es gehört
