### ISSUE TITLE
Getting no data with 1.2.0 and 1.2.1 with Firmware 1.7

### ISSUE THREAD

**Issue by Sev7eNup** [ioBroker/ioBroker#322]
I have to use Version 1.1.0 to get any data. Then its working for the BM-1, but there is no data for CGB-2, but a lot of errors in der ioBroker log like the following. Other people mentioned the issue already.

Version 1.2.1 does not work at all.

wolf.0 | 2021-02-16 12:08:59.038 | warn | (2481) Object wolf.0.hg1.9 is invalid: obj.common.type has an invalid value (state) but has to be one of number, string, boolean, array, object, mixed, file, json
-- | -- | -- | --
wolf.0 | 2021-02-16 12:08:59.038 | warn | (2481) This object will not be created in future versions. Please report this to the developer.
wolf.0 | 2021-02-16 12:08:59.037 | warn | (2481) Object wolf.0.hg1.8 is invalid: obj.common.type has an invalid value (state) but has to be one of number, string, boolean, array, object, mixed, file, json
wolf.0 | 2021-02-16 12:08:59.037 | warn | (2481) This object will not be created in future versions. Please report this to the developer.
wolf.0 | 2021-02-16 12:08:59.036 | warn | (2481) Object wolf.0.hg1.7 is invalid: obj.common.type has an invalid value (state) but has to be one of number, string, boolean, array, object, mixed, file, json
wolf.0 | 2021-02-16 12:08:59.036 | warn | (2481) This object will not be created in future versions. Please report this to the developer.
wolf.0 | 2021-02-16 12:08:59.035 | warn | (2481) Object wolf.0.hg1.6 is invalid: obj.common.type has an invalid value (state) but has to be one of number, string, boolean, array, object, mixed, file, json
wolf.0 | 2021-02-16 12:08:59.035 | warn | (2481) This object will not be created in future versions. Please report this to the developer.
wolf.0 | 2021-02-16 12:08:59.034 | warn | (2481) Object wolf.0.hg1.5 is invalid: obj.common.type has an invalid value (state) but has to be one of number, string, boolean, array, object, mixed, file, json
wolf.0 | 2021-02-16 12:08:59.034 | warn | (2481) This object will not be created in future versions. Please report this to the developer.
wolf.0 | 2021-02-16 12:08:59.033 | warn | (2481) Object wolf.0.hg1.4 is invalid: obj.common.type has an invalid value (state) but has to be one of number, string, boolean, array, object, mixed, file, json
wolf.0 | 2021-02-16 12:08:59.033 | warn | (2481) This object will not be created in future versions. Please report this to the developer.
wolf.0 | 2021-02-16 12:08:59.032 | warn | (2481) Object wolf.0.hg1.3 is invalid: obj.common.type has an invalid value (state) but has to be one of number, string, boolean, array, object, mixed, file, json
wolf.0 | 2021-02-16 12:08:59.032 | warn | (2481) This object will not be created in future versions. Please report this to the developer.
wolf.0 | 2021-02-16 12:08:59.031 | warn | (2481) Object wolf.0.hg1.2 is invalid: obj.common.type has an invalid value (state) but has to be one of number, string, boolean, array, object, mixed, file, json
wolf.0 | 2021-02-16 12:08:59.030 | warn | (2481) This object will not be created in future versions. Please report this to the developer.
wolf.0 | 2021-02-16 12:08:59.029 | warn | (2481) Object wolf.0.hg1.1 is invalid: obj.common.type has an invalid value (state) but has to be one of number, string, boolean, array, object, mixed, file, json

**Comment by Apollon77** [comment]
Please oopen the issue in the repository of the wolf adapter
