### ISSUE TITLE
 continuous loading when updating an adapter 

### ISSUE THREAD

**Issue by Siscop1** [ioBroker/ioBroker#323]
Hello,

everytime I try to download or update an Adapter it tells me that something is not installed and it tries to install it from source ending up in continuous loading and breaking up all the services. I have to pull the power and plug it back in and the adapter is running.
You can see the error message on the picture attached and the continuous loading circle.
Could please someone help me – it can not be good for the pi to always pull the plug.

Thank you

![manual inst](https://user-images.githubusercontent.com/68665800/108101983-46c34e80-7088-11eb-9c42-8265b83c5f26.png)

**Comment by Apollon77** [comment]
In fact it seems that your raspi do  not like building that one package.

And npm always detects that the package is missing and tries to build it.

Best do an "iobroker fix" and after that stop as many adapters as possible. Then try to install an adapter - hopefully now the memory is enough. In fact with a shell on that host and having "top" running there you see what happens. if a build process (or gcc, c++ or such) is there with high CPU load ... just let it run. Also check if memory becomes rare.

Ideally contact other community memmbers in forum to get a more detailed support.

**Comment by Siscop1** [comment]
iobroker stop - worked
iobroker fix - worked
iobroker start - worked
on GUI stopped some adapter - worked
on GUI installed control windows - worked no errors --- SUPER
now started all adapter again
on GUI installed octoprint // there is a octoprint support :-) - word no errors
on GUI uninstalled octoprint - worked
on GUI uninstalled control windows - warning with skipping optional dependencies... then the window vanished - however it worked

Seems like "iobroker fix" did the job. Thank you for your help.

**Comment by Apollon77** [comment]
glad to help
