### ISSUE TITLE
Feature Request: Alpine Linux support

### ISSUE THREAD

**Issue by dontobi** [ioBroker/ioBroker#327]
I have been running an ioBroker Docker image on Alpine Linux for a few days now. The container runs without problems, but the installer and the fix script do not support Alpine Linux. Would it be possible to add the alpine support?

**Comment by Apollon77** [comment]
What exactly is the issue with the installer? Error mesages? You're also welcome to support. Noone from us uses Alpine Linux so far ...

**Comment by dontobi** [comment]
1. Alpine does not use apt-get, but apk (https://wiki.alpinelinux.org/wiki/Alpine_Linux_package_management)

2. some packages are named differently. So I use the following packages for my Dockerfile:
acl avahi bash build-base cairo-dev coreutils curl eudev-libs gcc g++ giflib-dev git gnupg grep jq libcap libjpeg-turbo-dev linux-headers linux-pam-dev make net-tools pango-dev pkgconf pkgconfig procps python3 python3-dev util-linux shadow sudo tar tzdata unzip wget
librsvg-dev (from community repo)
gosu (from edge repo)


If it helps you, I can also send you the Dockerfile. I use the Dockerfile from buanet as a basis and have adapted it for an alpine arm container.

**Comment by Apollon77** [comment]
If you can write shell I would be havve to get a PR, else we need to see when someone finds time

**Comment by dontobi** [comment]
I can try, but for that I need to understand the existing script. Will therefore probably take longer. But maybe someone can help me.

**Comment by dontobi** [comment]
I'm closing here for the time being. The Zigbee adapter does not run under Alpine. The package libgdcm2-dev is missing under Alpine. Until I have found a workaround for this, I use Debian.
