### ISSUE TITLE
provisioning of instance settings (for adapters) from commandline

### ISSUE THREAD

**Issue by tillsteinbach** [ioBroker/ioBroker#332]
I'm looking for a way to provision ioBroker after container creation. I need to set instance settings from the commandline, but I'm not successful with it. Is there a way to do so without using a backup file?

**Comment by Apollon77** [comment]
What exactly is your usecase?

**Comment by tillsteinbach** [comment]
I have a docker container for iobroker and want to set adapter settings based on the docker configuration (e.g. from arguments or environment variables). I can set pretty much using the command line tool, but I have not found out how to set adapter settings from there. My current workaround is to manipulate objects.json, but this is a not so beautiful solution.

**Comment by Apollon77** [comment]
@GermanBluefox @buanet Any ideas from your side?

**Comment by buanet** [comment]
I don`t get the use case. What settings need to be provisioned?
Are we talking about adapter settings or general ioBroker settings?
Would be helpful to know what's the goal for this. Maybe @tillsteinbach can give us an example? 

Regards,
André

**Comment by tillsteinbach** [comment]
ok, one example: You have a swarm in docker-compose with a container with iobroker and a container with Influxdb. I provision a startup user script with iobroker to install the influx adapter, now what I want to do in this script also is setting the database host/user/password in the adapter using the data in environment variables from the swarm

**Comment by Apollon77** [comment]
Basically such stuff should be possible with CLI commands

like
`iobroker set admin.0 --port 8081` allows to set the common.port property of instance admin.0

When I know correctly this should also work for other data, just check the io-package.json from e.g, influxdb adapter in native section

**Comment by buanet** [comment]
@Apollon77
I can confirm this. Tried this with `iobroker set influxdb.0 --host 127.0.0.1`. Worked fine. 
As an example: For influxdb it should also be possible with the following parameters: 
```
  "native": {
    "debounce": "1000",
    "retention": "31536000",
    "dbname": "iobroker",
    "host": "influxdb",
    "protocol": "http",
    "port": "8086",
    "user": "mop",
    "password": "mup",
    "round": "4",
    "seriesBufferMax": "0",
    "seriesBufferFlushInterval": "600",
    "changesRelogInterval": "0",
    "changesMinDelta": "0",
    "reconnectInterval": 10000,
    "pingInterval": 15000
```

@tillsteinbach If this is the answer to your question feel free to close the issue. :)

Regards,
André

**Comment by tillsteinbach** [comment]
Ahrg! Now I feel silly! From the documentation of the command it looked like it does only accept the mentioned parameters. Works like a charm! Sorry causing work here!

**Comment by tillsteinbach** [comment]
Now I know why I was confused: It is only possible in the "set" command, not the "add" command. Would it be possible to have it there too?

**Comment by Apollon77** [comment]
add is just handing adapter and  instance installations and creation. This command do not set any values. If you like to have that added please create a feature request in js-controller repo to allow e.g. providing a json which is joined with the native part on the newly created instance or such

**Comment by tillsteinbach** [comment]
Understood, but it can set e.g. host and port?

**Comment by Apollon77** [comment]
> but it can set e.g. host and port?
... yes but only those two ... so the enhancement would be to make it more flexible and allow "any" parameter ...
