### ISSUE TITLE
Unexpected behavior when writing objects from javascript

### ISSUE THREAD

**Issue by tillsteinbach** [ioBroker/ioBroker#333]
I try to write custom data on objects through the javascript API. Background is: I want to add storage settings automatically for certain objects.
I experience strange behaviour when writing the settings and reading the object back. Especially it is impossible to delete thecustom configuration again.

See attached example code

[example.js.txt](https://github.com/ioBroker/ioBroker/files/6299624/example.js.txt)

**Comment by Apollon77** [comment]
If the influxdb/hostory/sql Adaters are running you can send messages to the adapter to change the settings.

If you really need to manually edit the settings you need to set the value as "null" to remove it - else the default behaviour is to preserve custom settings.

so to delete use

```
objectToChange.common.custom[influxInstance] = null;
```
