### ISSUE TITLE
iobroker update fails

### ISSUE THREAD

**Issue by louisvangeldrop** [ioBroker/ioBroker#335]
Running: iobroker update results in:

iobroker update
No connection to databases possible ...
 Unable to subscribe to expiry Keyspace events from Redis Server: Connection is closed.

I don't understand this message since I am not using Redis.

Maybe it has to do with the backup-adapter. I have once accidently selected Redis in the backup-options and tried to make a backup. It failed, because I am not using Redis.

**Comment by Apollon77** [comment]
Here we need way mofe informations ... could you come to the Forum because Ithink this is better handled there.

Other way: please post output of "iobroker status" and "iobroker version"

**Comment by louisvangeldrop** [comment]
pi@raspberrypi:/opt/iobroker $ iobroker status
iobroker is running on this host.


Objects type: file
States  type: file


pi@raspberrypi:/opt/iobroker $ iobroker -v
3.2.16

**Comment by Apollon77** [comment]
is the host busy somehow? This normally only happens if the db cannot be started withing some seconds ...

The info on redis can be ignored, because also file db is using redis protocols internally

**Comment by louisvangeldrop** [comment]
I have waited at least 30 minutes. Same error. The problem occurred after wrongly using the backup adapter.

**Comment by Apollon77** [comment]
"wrongly using backitup"?? means what?

**Comment by louisvangeldrop** [comment]
Maybe it has to do with the backup-adapter. I have once accidently selected Redis in the backup-options and tried to make a backup. It failed, because I am not using Redis.

**Comment by Apollon77** [comment]
That shoukd not have any effect

**Comment by Apollon77** [comment]
but ok then lets try the bit "harder way" and see if it helps:

Edit /opt/iobroker/iobroker-data/iobroker.json

and under objects and states you see a

"connectTimeout": 2000,

change to 5000.

Does it work then?

**Comment by louisvangeldrop** [comment]
SUPER. Now it works. Thanks a lot
