### ISSUE TITLE
diag data transmission before License agreement

### ISSUE THREAD

**Issue by derlucas** [ioBroker/ioBroker#339]
Hey ioBroker,
i tried the ioBroker docker container for the first time and noticed the Log showing the following:

```
host.XXXX check instance "system.adapter.info.0" for host "XXXXX"
Send diag info: {"uuid":"****","language":"","country":"","hosts":[{"version":"3.2.16","platform":"Javascript/Node.js","type":"linux"}],"node":"v12.22.1","arch":"x64","adapters":{"admin":{"version":"4.2.1","platform":"Javascript/Node.js"},"discovery":{"version":"2.6.1","platform":"Javascript/Node.js"},"info":{"version":"1.7.14","platform":"Javascript/Node.js"}},"statesType":"file","objectsType":"file","model":"AMD Ryzen 9 3950X 16-Core Processor","cpus":32,"mem":33650028544,"ostype":"Linux","city":""}
hash changed or no sources cached => force download of new sources
```

i have not opened the Admin UI and Accepted the red Check box for the License Agreement. So IMHO i did not give my consent to send statistics to the project. To make sure, it is actual transmitting Data, i checked with Wireshark and i can see the HTTP request with the JSON Data to the IP 79.143.182.215

I understand that the Data is not that critical, but then the UI is giving the wrong impression. At least before i accepted the License, there should not be any data reporting.

The data reporting and accepting of the license should not be in one single checkbox.

I'm sorry that my first Issue in this project is this nasty topic DSGVO/GDPR.

Lucas

**Comment by Apollon77** [comment]
@derlucas We will fix this with js-controller 3.3.10 later today which is then first in "Latest" repository. Will be fixed for all users when this controller becomes the stable version (in 2.4 weeks hopefully.

Thank your for bringing it up.
