### ISSUE TITLE
fritzdect.0 warn

### ISSUE THREAD

**Issue by poand** [ioBroker/ioBroker#341]
Hello ladies and gentlemen,

Rademacher RolloTron DECT 1213 are operated via Fritz! Box.

The following message appears in the "Log" of ioBroker: 
- (794) State "fritzdect.0.DECT_142760470432-1.mode" has no existing object, this might lead to an error in future versions
- (794) unknown datapoint DECT_142760470432-1.endpositionsset please inform devloper and open issue in github

**Comment by Apollon77** [comment]
Please create the issue in the repository of the adapter
