### ISSUE TITLE
IOBroker crasht beim Backup

### ISSUE THREAD

**Issue by Bjoern2006** [ioBroker/ioBroker#348]
Seit einiger Zeit habe ich das Problem, das ein Backup meines IOBroker Systems nicht mehr möglich ist. Weder übers Terminal (siehe Screenshot), noch über den BackItUp Adapter.

![image](https://user-images.githubusercontent.com/28015256/129340773-88712999-4b3d-4ce7-badd-4305c30e7399.png)

Kann damit jemand was anfangen und ggf. helfen?
Ich hatte die Idee, das die Datenbank einen Knacks hat, aber kenn mich da zu wenig aus um das A sagen zu können und B um ggf. den Fehler auch beheben zu können.

Sollten noch Informationen benötigt werden, einfach Bescheid geben.

**Comment by Apollon77** [comment]
Wird das Backup generell erstellt? Effektiv ist es hier so das die Datenbank - nach dem Speichern der Daten scheinbar zu schnell "weg" ist. Das habe ich noch nie gesehen.

Läuft der iobroker wenn Du das tust? Falls ja: Passiert es auch wenn er aus ist?

**Comment by Bjoern2006** [comment]
> Wird das Backup generell erstellt? Effektiv ist es hier so das die Datenbank - nach dem Speichern der Daten scheinbar zu schnell "weg" ist. Das habe ich noch nie gesehen.
> 
> Läuft der iobroker wenn Du das tust? Falls ja: Passiert es auch wenn er aus ist?

Nein das Backup wird nicht erstellt.
Ja der IOBroker läuft während des Backups.
Wenn der IOBroker gestoppt ist passiert folgendes:
![IMG_20210813_130504_722.png](https://user-images.githubusercontent.com/28015256/129348078-34eba6c5-4b3c-4dfc-bb67-cc71492a8e6a.png)

**Comment by Apollon77** [comment]
Ok, this error I "hoped for".Check your free RAM please. It seems that your system is very low on available RAM.

I expect from the first tries you will find "oom" (out of memory) logs in /var/log/syslog that the iobroker proces was killed because of too less ram.

Could that be? Check "free -m" please

**Comment by Bjoern2006** [comment]
Ich habe den Befehl "free -m" ausgeführt:
![image](https://user-images.githubusercontent.com/28015256/129359502-e814a5fe-b09a-468d-920b-52bb70ed0efd.png)

**Comment by Bjoern2006** [comment]
> Ok, this error I "hoped for".Check your free RAM please. It seems that your system is very low on available RAM.
> 
> I expect from the first tries you will find "oom" (out of memory) logs in /var/log/syslog that the iobroker proces was killed because of too less ram.
> 
> Could that be? Check "free -m" please

Ich hab mal den Teil aus dem Syslog kopiert, von dem Zeitraum in dem ich das heute getestet hab.
Lässt sich da was heraus lesen?
[Syslog.txt](https://github.com/ioBroker/ioBroker/files/6982521/Syslog.txt)

**Comment by Apollon77** [comment]
Was ist denn das für ein System ? Wieviel RAM?
Du hast 29 Adapterinstanzen ... Rechnerisch braucht jede mindestens 50MB ... Dein System sollte also mindestsns 2GB RAM haben ... hat es das?
Ok laut dem "free -m "oben sind es 8GB ... das sollte locker reichen

> Aug 13 11:36:16 raspberrypi kernel: [665901.755791] iobroker.js-con invoked oom-killer: gfp_mask=0xcc0(GFP_KERNEL), order=0, oom_score_adj=0

Da isser ja der OOM Killer ... Der killt dir prozesse ...

Auch du guter gott .. da ist ja alles und nix drauf (also zum zeitpunkt des OOMs)? mySQL, Anydesk, VNC, ein X11, mehrere chromium browser tabs, apache ...

ein anderes mal laut log hat er dir eine chromium browser tag gekillt:
> Aug 13 11:36:17 raspberrypi kernel: [665902.712798] oom_reaper: reaped process 3462 (chromium-browse), now anon-rss:0kB, file-rss:0kB, shmem-rss:2412kB

also ... finde raus was da RAM technisch ist und räum auf bitte

**Comment by Topper-Harley-NO** [comment]
Hallo, ich würde gern wissen, ob dieses Problem gelöst wurde. Ich hab seit zwei Monaten das selbe Problem und ich hatte gehofft, das eventuell Updates, das Problem lösen würden.
Es sind genau die selben Probleme, wie oben beschrieben. Egal ob über "BackitUp", oder direkt über Konsole.

Raspberry 4 4GB RAM
26 Instanzen
RAM-Auslastung 35% (noch 65% frei)
