### ISSUE TITLE
ioBroker LOG Info while using iPhone ioBroker vis-App 

### ISSUE THREAD

**Issue by lumpers** [ioBroker/ioBroker#350]
while using iPhone ioBroker vis-App with configured setting: "Batteriestatus in vis.0 aktivieren" the following 
log entry is reported after web access:
**State value to set for "vis.0.SmartPhone.battery.state" has to be type "string" but received type "number"**
Additional result:
The datapoints (vis.0.SmartPhone.battery.level, vis.0.SmartPhone.battery.state) in vis.0 are present but will not be updated.

Versions:
JS-Controller version: 3.3.15
Node version: v12.22.5
npm-Version: 6.14.14
ioBroker App version at iPhone X: 1.0.25
Operating system: Linux -> RP4

**Comment by Apollon77** [comment]
Please open this issue in vis or with the used vis widget repository which is used to change this value
