### ISSUE TITLE
Could not retrieve token, Error from Tesla: No response

### ISSUE THREAD

**Issue by jensb** [ioBroker/ioBroker#351]
I have been running 0.5.2 on iobroker for months without issues.

Two days ago, right in the middle of our vacation, I noticed iobroker was not monitoring our car any more. So I looked and there was only garbage in the "token" field of the adapter configuration. Any action produced the error in the title. Requesting a new token also did not work, neither did I find a way to reset the adapter to its defaults. Updating to 0.5.5 did not change the error message either.
So I completely deinstalled tesla-motors (not just the instance, the whole adapter) and reinstalled it - but I *still* get the above error message.
Setting the log level to "silly" does not produce any additional errors.

What can be the cause of this? I can log in using the Tesla app or the website with the same credentials.

**Comment by Apollon77** [comment]
please open issue with the tesa adapter repository

**Comment by jensb** [comment]
Argh. sorry, wrong link. it was late yesterday. :-(
