### ISSUE TITLE
Hue-extended sendet falschen Datentyp

### ISSUE THREAD

**Issue by bz7i** [ioBroker/ioBroker#355]
Moin,

ich bekomme seid einiger Zeit vom Hue-extended Adapter die Meldung das der Datentyp falsch ist.
Weiß jemand wie Ich das abstellen kann ?

<html>
<body>

hue-extended.0 | 2021-09-12 09:46:44.183 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_max" has to be type "string" but received type "number"
-- | -- | -- | --
hue-extended.0 | 2021-09-12 09:46:44.182 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2021-09-12 09:46:44.037 | info | State value to set for "hue-extended.0.sensors.003-hue_outdoor_ambient_light_sensor.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2021-09-12 09:44:42.985 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2021-09-12 09:44:42.875 | info | State value to set for "hue-extended.0.sensors.037-hue_outdoor_ambient_light_sensor.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2021-09-12 09:42:11.491 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_min" has to be type "string" but received type "number"
hue-extended.0 | 2021-09-12 09:42:11.489 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2021-09-12 09:42:11.358 | info | State value to set for "hue-extended.0.sensors.052-hue_ambient_light_sensor_1.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2021-09-12 09:41:41.208 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_max" has to be type "string" but received type "number"
hue-extended.0 | 2021-09-12 09:41:41.208 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2021-09-12 09:41:41.080 | info | State value to set for "hue-extended.0.sensors.003-hue_outdoor_ambient_light_sensor.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2021-09-12 09:39:40.031 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2021-09-12 09:39:39.916 | info | State value to set for "hue-extended.0.sensors.037-hue_outdoor_ambient_light_sensor.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2021-09-12 09:37:08.635 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_min" has to be type "string" but received type "number"
hue-extended.0 | 2021-09-12 09:37:08.593 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2021-09-12 09:37:08.470 | info | State value to set for "hue-extended.0.sensors.052-hue_ambient_light_sensor_1.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2021-09-12 09:36:38.255 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel_max" has to be type "string" but received type "number"
hue-extended.0 | 2021-09-12 09:36:38.253 | info | State value to set for "hue-extended.0.groups.000-all_lights.lightlevel.state.lightlevel" has to be type "string" but received type "number"
hue-extended.0 | 2021-09-12 09:36:38.182 | info | State value to set for "hue-extended.0.sensors.003-hue_outdoor_ambient_light_sensor.state.lightlevel" has to be type "string" but received type "number"

</body>
</html>

**Comment by AlCalzone** [comment]
Bitte issue im repo für den Hue-extended adapter aufmachen.
