### ISSUE TITLE
cronjobs broken on Raspberry Pi 4

### ISSUE THREAD

**Issue by n0valis** [ioBroker/ioBroker#360]
I run serveral blockly scripts with timers.
None of the timers are on time.
I run a test script,
timers are supposed to be executed every full hour, here is how it looks:
`javascript.1 2021-10-20 14:08:04.479 info script.js.common.TestTimer: test on14:08:04
javascript.12021-10-20 13:01:01.529 info script.js.common.TestTimer: test on13:01:01
javascript.1 2021-10-20 12:07:35.291 info script.js.common.TestTimer: test on12:07:35
javascript.1 2021-10-20 11:04:11.698 info script.js.common.TestTimer: test on11:04:11
javascript.1 2021-10-20 10:29:30.745 info script.js.common.TestTimer: test on10:29:30`

This looks pretty much the same every day. 

Systemtime is not the issue. I checked that and it is always absolutely correct.
It seems that if I re-save my script shortly before the scheduled time, the timer would be executed correctly.

RPi 4 DietPi Bullseye
ioBroker 5.1.25
Nodejs 12.22.6
npm 6.14.15

**Comment by Apollon77** [comment]
Please open the issue in the repository of the javascript adapter ... and please post the script, because else this output con come from anything
