### ISSUE TITLE
"Save" on all levels of editing within iobroker-administration

### ISSUE THREAD

**Issue by astrakid** [ioBroker/ioBroker#361]
In an issue for iqontrol the developer stated, that this is a restriction of the iobroker framework.

When changing details in an object you need to submit all changes by pressing "ok" for getting back to the main iqontrol-admin screen and save those changes. that makes it uncomfortable for testing changes.

open iqontrol administration
open a device
e.g. open "additional_control"
change something
for submitting the changes you have to press ok in "additiional_control edit window"
then you have to press "ok" once again to get back to iqontrol admin main screen
press "save"
Expected behavior

it would be very comfortable to get the save button on all levels of editing, to be able to quickly submit changes, check the results and edit again.

**Comment by Apollon77** [comment]
Best would be that the developer of the adapter opens an issue with exactly what he needs in admin adapter.

**Comment by astrakid** [comment]
ok, thx. i asked the developer to provide that information.
