### ISSUE TITLE
Request: Make RootURL for iobroker/vis customizeable

### ISSUE THREAD

**Issue by alexpthe1** [ioBroker/ioBroker#362]
While setting up a ReverseProxy i have seen that some requests are (obviuosly) hardcoded to the root. 
For Example:

- /?sid=XXXXXXXX&name=admin from socket.io:91
- /login?href=#tab-intro

It would be great to customize the root directory so these requests dont have to be re-written

**Comment by Apollon77** [comment]
Depending on where it is relevant please create tickets in web, admin and/or socket.io daspters
