### ISSUE TITLE
stuck on /#tab-intro after update

### ISSUE THREAD

**Issue by nicedevil007** [ioBroker/ioBroker#363]
Hi, I recently updated the admin adapter to the latest version (5 minutes ago) and now my ioBroker isn't loading at all....

It is stuck on this page:

![image](https://user-images.githubusercontent.com/17103076/143585443-46a01b6e-d1e2-42e5-8b67-659a4c151102.png)

How can this be fixed?
My ioBroker is deployed inside a docker container.

**Comment by thost96** [comment]
Hi, this error is related to admin, so please see https://github.com/ioBroker/ioBroker.admin/issues/1213

**Comment by Apollon77** [comment]
Admin 3.2.0 fixes this issue
