### ISSUE TITLE
Feature Request: Hinzufügen von weiteren Gerätetypen unter "Geräte"

### ISSUE THREAD

**Issue by FISO291** [ioBroker/ioBroker#364]
Hallo, 

ist es möglich, dass Ihr unter Geräte die Kategorie "Wechselrichter" , "Stromzähler" und "Wasseruhr" hinzufügen könntet? Ich wusste nicht was ich für diese Kategorie auswählen soll, daher habe ich - auch wenns bescheuert ist - die Gerätekategorie "Steckdose" genommen (Wechselrichter und Stromzähler) und bei Wasseruhr "Info". weil die recht gut passt.

Falls es möglich wäre, könnte ich noch mehr Details posten wie ich mir das Vorstelle :)

Ich danke schonmal im Vorraus für eine Antwort.

**Comment by Apollon77** [comment]
Bitte das Issue im Repo des Devices Adapter öffnen, aber macht nur sinn auch mit Info welche Datenpunkte solche Geräte haben sollten
