### ISSUE TITLE
install fixer not working properly

### ISSUE THREAD

**Issue by passuff** [ioBroker/ioBroker#371]
If I try to execute the install fixer (curl -sL https://iobroker.net/fix.sh | bash-) with  iobroker stopped I get the following error message:

`-bash: bash-: Kommando nicht gefunden.`

It actually works if I dont stop iobroker before.

My system:

Platform       : linux
os             : linux
Architecture   : x64
CPUs           : 2
Speed          : 1699 MHz
Model          : Common KVM processor
RAM            : 7.7 GB
System uptime  : 8d. 14:22:41
Node.js        : v12.22.5
time           : 1644188242976
timeOffset     : -60
adapters count : 472
NPM            : v7.5.2
Disk size      : 30.4 GiB
Disk free      : 26.6 GiB
js-controller v4.04

EDIT: If I use "iob fix" everything is working fine...

**Comment by Apollon77** [comment]
Question is where this comes from ... also the file to download do not contain "bash-" ... only "bash -"

**Comment by passuff** [comment]
I can no longer understand it at the moment. Maybe it was just a typo but actually I doubt that. After the fixer was executed, it is working for me now even with a stopped iobroker. 
You can close the topic because it looks like it was a user fault ;)
Thank you

**Comment by Apollon77** [comment]
Ok, strange
