### ISSUE TITLE
Unable to select Install GitHub Adapter

### ISSUE THREAD

**Issue by tmycgn** [ioBroker/ioBroker#388]
Unfortunately I am not able to select an adapter via the GitHub install pulldown. Seems to have something to do with the newly installed ioBroker version 6. :(

```
ARMv7 Processor rev 3 (v7l)
Node.js v14.19.3
NPM 6.14.14
ioBroker 6.0
```

![image](https://user-images.githubusercontent.com/82310796/172041977-3116bcfc-5328-4984-8a91-c51ac6c1f6e5.png)

**Comment by Apollon77** [comment]
Already known as Admin 6 issue
