### ISSUE TITLE
Windows-Installer (2022) - Version numbering

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker#389]
The "old" windows installer dated from 2019 states its version number as 2.1.0.b.
The new (2022) windows installer states its version as 1.0.1.
See screenshots.

![installer-2019](https://user-images.githubusercontent.com/28575778/172396126-1079b4e2-5eb8-4177-8f4d-02b4100224d3.jpg)
![installer-2022](https://user-images.githubusercontent.com/28575778/172396146-b0561c1c-014b-4463-8ca1-7f124f3a879a.jpg)

In my opinion the new installer should have a higher major versionnumer to avoid confusion.

In addition I would suggest to add the version number into the windows executabale file name. This would ensure that downloads can be more easily be identified later.

McM

**Comment by Gaspode69** [comment]
Can be closed. We are at version 3.3.0 with the latest installer.
