### ISSUE TITLE
Adapter installation with admin is not possible under FreeBSD

### ISSUE THREAD

**Issue by cernst1980** [ioBroker/ioBroker#39]
ioBroker is started with the following command under FreeBSD

su -m iobroker -c "${command} /opt/iobroker/node_modules/iobroker.js-controller/iobroker.js start"

"su -m" leaves the environment unmodified, also $HOME

When trying to install an adapter with admin adapter web interface, npm throws an EACCESS error because directory /.npm or /.config is not writable.

$ su -m iobroker -c 'env | grep HOME'
HOME=/root

Default cache directory for npm is ~/.npm --> /.npm in this case.

Workarounds: Login shell for user iobroker or usage of sudo instead of su

**Comment by cernst1980** [comment]
Fixed in https://github.com/ioBroker/ioBroker/pull/37/commits/3a0ed974a5368ab0397cc057908c4511b6ed7382

**Comment by Apollon77** [comment]
I will merge anything hopefully tomorrow and can release 1.0.7
