### ISSUE TITLE
Install ioBroker on Synology without docker

### ISSUE THREAD

**Issue by svsorokina** [ioBroker/ioBroker#390]
Hi everyone!
Is it possible to install ioBroker on Synology without docker. I have DS116 with DSM 7.0.
Node.js version 16 installed.
I tried execute under root `curl -sLf https://iobroker.net/install.sh | bash -` but got several errors.

```
main: line 638: useradd: command not found

User iobroker created

main: line 681: visudo: command not found

Fixing directory permissions...

chown: invalid user: ‘iobroker:iobroker’

chown: invalid user: ‘iobroker:iobroker’

This system does not support setting default permissions.
```

`systemctl status -l iobroker.service` output is

```
iobroker.service - ioBroker Server
   Loaded: loaded (/usr/lib/systemd/system/iobroker.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2022-06-26 17:23:35 +03; 2s ago
     Docs: http://iobroker.net
  Process: 10779 ExecStart=/bin/bash -c ${NODE} /opt/iobroker/node_modules/iobroker.js-controller/controller.js (code=exited, status=217/USER)
 Main PID: 10779 (code=exited, status=217/USER)

Jun 26 17:23:35 DS116 systemd[1]: Unit iobroker.service entered failed state.
Jun 26 17:23:35 DS116 systemd[1]: iobroker.service failed.
```

Can anyone help with this?

UPD: I fixed error with user. Created it manually in system. But got another error and have no idea how to fix this.

```
main: line 681: visudo: command not found
Fixing directory permissions...
This system does not support setting default permissions.
```

`systemctl status -l iobroker.service`

```
● iobroker.service - ioBroker Server
   Loaded: loaded (/usr/lib/systemd/system/iobroker.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2022-06-26 19:07:24 +03; 1s ago
     Docs: http://iobroker.net
  Process: 30694 ExecStart=/bin/bash -c ${NODE} /opt/iobroker/node_modules/iobroker.js-controller/controller.js (code=exited, status=1/FAILURE)
 Main PID: 30694 (code=exited, status=1/FAILURE)

Jun 26 19:07:24 DS116 systemd[1]: Unit iobroker.service entered failed state.
Jun 26 19:07:24 DS116 systemd[1]: iobroker.service failed.
```

**Comment by Apollon77** [comment]
Because of the fact that the Synology DSM is not a "real full linux" I assume it will be a challenge to get it running and is more a forum topic then an issue. I would not do it honestly, on NAS the docker way is the favorite one

**Comment by buanet** [comment]
@svsorokina Please, really don't do that local installation! Synology will not take care of that and might simply overwrite your installation with the next DSM Update.... 
Best way to run ioBroker on a nas is Docker. Another way will be running i inside a [virtual machine](https://www.synology.com/de-de/dsm/feature/virtual_machine_manager) . If you need any help post a topic at the ioBroker Forum or join the ioBroker Discord Community. 

Regards, 
André
