### ISSUE TITLE
Multiple browser sessions are no longer possible

### ISSUE THREAD

**Issue by MosizZ** [ioBroker/ioBroker#398]
since updating to Node.jsv16.18.0/NPM8.19.2 I can no longer open multiple browser tabs in ioBroker. More precisely. Opening and logging in works, only the session of the "older" tab is ended a short time later. the behavior can be reproduced independently of the browser and operating system.

**Comment by Apollon77** [comment]
Do you talkt about sessions in Admin or anything via "web" adapter? Plesse open the issue in the respoective adapter repo

**Comment by MosizZ** [comment]
It doesn't matter whether I'm in the admin overview twice or once in admin and once in Javascript Adapter, for example

**Comment by Apollon77** [comment]
Ok, so all Admin. Please open the issue in ioBroker.admin reposiory

**Comment by MosizZ** [comment]
I only understood what you meant after the second reading. I open the issue in ioBroker.admin
