### ISSUE TITLE
Fedora installation does not work

### ISSUE THREAD

**Issue by cmuellner** [ioBroker/ioBroker#42]
I've tried to install iobroker on a Pine64 (aarch64), which runs Fedora 27, but I'm failing because the installer requires `update-rc.d`, which is not existing in Fedora.

```
npm install iobroker.admin --production --save --prefix /opt/iobroker
npm install iobroker.js-controller --production --save --prefix /opt/iobroker
npm WARN deprecated localhost.daplie.me-certificates@1.3.5: this package has been deprecated
Write "./iobroker start" to start the ioBroker
/opt/iobroker/node_modules/iobroker/lib/../install/linux/install.sh: line 61: update-rc.d: command not found
Auto-start was enabled. Write "update-rc.d -f iobroker.sh remove" to disable auto-start
iobroker is started. Go to "http://ip-addr:8081" to open the admin UI.
iobroker@1.0.8 node_modules/iobroker
└── yargs@7.1.0 (get-caller-file@1.0.2, decamelize@1.2.0, y18n@3.2.1, camelcase@3.0.0, which-module@1.0.0, set-blocking@2.0.0, yargs-parser@5.0.0, require-main-filename@1.0.1, require-directory@2.1.1, os-locale@1.4.0, cliui@3.2.0, string-width@1.0.2, read-pkg-up@1.0.1)
```

**Comment by Apollon77** [comment]
Hm ... the only this which is failing and you need to do manually in your case is to make sure ioBroker can start automatically on system start.
All the rest should be fine

**Comment by cmuellner** [comment]
More or less all Linux distributions (even Buildroot) support systemd nowadays. Maybe a systemd-based startup script would be a benefit for ioBroker.

**Comment by Apollon77** [comment]
Yes, but mostly systemd offers compatibility modes :-)
If you know how the service description needs to be and how to distinguish between systemd and other ways ... a PR is welcome

**Comment by Apollon77** [comment]
should be fixed in current installers
