### ISSUE TITLE
iobroker mqtt adapter issues with json strings > possible to separate into signle states?

### ISSUE THREAD

**Issue by rantwolf** [ioBroker/ioBroker#425]
Hi.
I hope this is the right place for my question.
I'm relative new to iobroker.
I have some power plugs, a sonoff zigbee bridge pro with connected sensors and a sonoff rf bridge all flashed with tasmota.

I know all mqtt messages are json strings.

When I'm using the sonoff adpater (as mqtt broker) all incoming mqtt states will be formatted from json and saved as separated values.
This is very nice but I can't use non default tasmota mqtt topics.
Also I can connect desktop mqtt client such as 'mqtt explorer' but there is no message visible.

If I switch to the mqtt adpater the things above are working.
But now my biggest problem is, that all messages are saved as json-string.

Is there a way to convert/separate and save all incoming states/sensors/results as single values?
I found some scripts to separate the strings.
But thats not helpful, because i have to write one script for every json-string.

**Comment by Apollon77** [comment]
You would need to write own javascript scripts that subscribe to the mqtt adapter states and then store the data in whatever structure you need. I thinjk it is best to check in forum for support on "how"

**Comment by FMode** [comment]
I am just doing this in javascript incl. creation of an Alias (with seperate read/write ids) for correct handshake.
I am not sure if this is feasible to do with a type "json_interpreted" because tasmota is not creating every usable topic.

Yes I create the states automatically by parseing the json.
