### ISSUE TITLE
Backup nicht möglich

### ISSUE THREAD

**Issue by andybali** [ioBroker/ioBroker#43]
"iobroker backup" und/oder "node /opt/iobroker/node_modules/iobroker.js-controller/iobroker.js backup"
wird gekillt

root@orangepiplus2e:~# iobroker backup
/usr/bin/iobroker: line 1: 20222 Killed node /opt/iobroker/node_modules/iobroker.js-controller/iobroker.js $1 $2 $3 $4 $5

http://forum.iobroker.net/viewtopic.php?f=17&t=11849

**Comment by Apollon77** [comment]
If still relevant please crate issue in https://github.com/ioBroker/ioBroker.js-controller/issues including used version of js-controller
