### ISSUE TITLE
FR: allow mqtt clients to ignore certificate validation

### ISSUE THREAD

**Issue by andreklug** [ioBroker/ioBroker#430]
this is related to https://forum.iobroker.net/topic/62986/mqtt-client-error

I cannot use the iobroker MQTT client to connect to my MQTT server, which is using a certificate from my certificate authority that I am using for all services in my network.
Please allow either to add a trusted root certificate to the configuration (preferred) or add an option to skip certificate validation at all.

**Comment by Apollon77** [comment]
Please eopen this issue in the repo of the used mqqt adapter
