### ISSUE TITLE
common.messagebox has no effect

### ISSUE THREAD

**Issue by crosenbe** [ioBroker/ioBroker#431]
Setting common.messagebox to true in io-package.json has no effect. Using sendTo oder selectSendTo does not trigger a message.

node 16.19.0
ioBroker 4.0.24

`# iobroker message <myadapter> send test`

does not trigger a message either.

Code extract ...
```
class TestAdapter extends utils.Adapter {
  constructor (options) {
    super({
      name: 'testadapter'
    })
    this.on('ready', this.onReady.bind(this))
    this.on('stateChange', this.onStateChange.bind(this))
    this.on('message', obj => this.onMessage(obj))
    this.on('unload', this.onUnload.bind(this))
  }

  // If you need to accept messages in your adapter, uncomment the following block and the corresponding line in the constructor.
  // /**
  //  * Some message was sent to this instance over message box. Used by email, pushover, text2speech, ...
  //  * Using this method requires "common.messagebox" property to be set to true in io-package.json
  //  * @param {ioBroker.Message} obj
  //  */
  
  
  async onMessage(obj) {
    this.log.debug('called onMessage')
  }
}
```

**Comment by Apollon77** [comment]
Did you do an "iob upload adaptername" and a restart of the adapter and pot whole iobroker after you added this to your io-package??

**Comment by crosenbe** [comment]
I did "dev-server upload" which is not the same. "iob upload adaptername" solved this issue. Thanks a lot pointing this out. I didn't recognize what is exactly happing with this upload command, maybe some registering process in iobroker-data.

**Comment by Apollon77** [comment]
normally dev-server upload should do the same ... but glad it worked now
