### ISSUE TITLE
npm Module not found

### ISSUE THREAD

**Issue by AceTecNic** [ioBroker/ioBroker#439]
Hallo zusammen,
Bei meiner installation auf Windows Server 2019 bekomme ich ständig probleme mit npm.
Beim Installieren von vis oder jetzt bei vis-timeandweather kommt folgende Fehlermeldung:

`C:\iobroker\SchmidControlSystem>npm install iobroker.vis-timeandweather
internal/modules/cjs/loader.js:934
  throw err;
  ^

Error: Cannot find module 'C:\iobroker\SchmidControlSystem\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:934
  throw err;
  ^

Error: Cannot find module 'C:\iobroker\SchmidControlSystem\node_modules\npm\bin\npm-cli.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:774:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}`

Kann mir jemand weiterhelfen?

Neuinstallation von Node-v14 bringt nur für einen Moment etwas, beim installieren vom nächsten Adapter is das gleiche wieder...

Windows Server 2019
Node 14.21.3
IOB 4.0.24
Vis 1.4.16

**Comment by Apollon77** [comment]
In dem Fall ist wohl die NPM installaton selbst kaputt oder passt nicht zur node.js version. Ist das ggf eine "alte" Windowsinstallation mit dem" alten installer? Dann bitte -> Forum!! Da muss man auch nodejs anders aktualisieren und so ... 

Weiterhin: Warum nutzt du überhaupt die kommandozeile? Kommt mit Admin der gleiche fehler? Wenn ja ok ansonsten IMMER adapter via Admin installieren!

**Comment by AceTecNic** [comment]
Die Installation selbst funktioniert und ist nicht kaputt und passt meines Wissens nach zur node.js Version. Habe diese über die Node.js Homepage heruntergeladen.

Was ich jetzt beobachtet habe:
C:\iobroker\iobname\node_modules\npm
Nach hinzufügen eines Adapter (egal ob via Admin oder nodejs-cmd) wird der Ordner gelöscht und ein weiteres hinzufügen von Adaptern ist nicht mehr möglich.

Meine Lösung:
NodeJS installer reparieren lassen nach jedem hinzugefügtem Adapter in iob.

Keine Ahnung von welcher Seite aus das Problem verursacht wird...
Danke

**Comment by Apollon77** [comment]
Bitte im Forum nach Rat bei den Windowsexperten suchen!
