### ISSUE TITLE
iobroker install script issue - old node version - iob doesn't start

### ISSUE THREAD

**Issue by xmace** [ioBroker/ioBroker#440]
Installer version: 2022-12-22
new installation on rpi zero 2w

==========================================================================
    Installing ioBroker (3/4)
==========================================================================

npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: fs-extra@11.1.1
npm ERR! notsup Not compatible with your version of node/npm: fs-extra@11.1.1
npm ERR! notsup Required: {"node":">=14.14"}
npm ERR! notsup Actual:   {"npm":"7.5.2","node":"v12.22.12"}

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-04-06T09_49_08_476Z-debug.log

---------------------------------------------------------------------------------------------

root@raspberrypi:/home/pi# iobroker status
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/opt/iobroker/node_modules/iobroker.js-controller/iobroker.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
root@raspberrypi:/home/pi# node -v
v12.22.12

BR, xmace

**Comment by Apollon77** [comment]
Yes you are right ... the bakckitup adapter prevents the installation in this case. Please update your nodejs. 

Very soon js-controller 5.0 will come and this also skips support for nodejs 12.

Node.js 12 is EOL since 1 year now.
