### ISSUE TITLE
Unsicheres Besitzverhältnis des Home-Verzeichnis trotz iobroker.net/fix.sh

### ISSUE THREAD

**Issue by ioBroker22** [ioBroker/ioBroker#445]
Beim Update/der Installation von Node.js 18 (anscheinend auch bei 16, ist mir nur vorher nie aufgefallen) bringt die Konsole folgende Warnung:
`+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | gpg --dearmor | tee /usr/share/keyrings/nodesource.gpg >/dev/null
gpg: WARNUNG: Unsicheres Besitzverhältnis des Home-Verzeichnis "/home/pi/.gnupg"`
Ich lasse grundsätzlich den aktuellen Fixer drüber laufen, wobei ich dachte, dass dieser solche Probleme lösen würde. Ich nutze dafür folgenden Befehl:
`curl -sL https://iobroker.net/fix.sh | bash -`
ls -la zeigt mir für .gnupg
`drwx------ 3 pi   pi    4096 Nov 27  2019 .gnupg`
und für den Ordner pi
`drwxr-xr-x  8 pi       pi       4096 Apr  9 07:10 pi`
Natürlich kann ich jetzt so lange an den Rechten rumbasteln, bis die Warnung verschwindet. Aber vielleicht hat ja jemand einen Tipp wie ich das lösen kann ohne was zu zerstören. Oder möglicherweise kann auch der Fixer geupdated werden um das Problem zu beheben.

Vielen Dank!

**Comment by Apollon77** [comment]
/home/pi/.gnupg hat nichts mit iobroker zu tun und damit fasst der Fixer da auch nichts an. Das musst DU also bitte selbst lösen weil auch der installer oder fixer das nicht direkt abngelegt hat und auch der Fixer sich nur an den Rechten von "seinen" Verzeichnissen vergreift.

**Comment by Apollon77** [comment]
Falls Du Support brauchst wäre das Forum ggf die beste anlaufstelle
