### ISSUE TITLE
Error message: Cannot read disk size: Error: spawn ENOMEM

### ISSUE THREAD

**Issue by K2ij3** [ioBroker/ioBroker#450]
I have error messages in the log and no idea how to solve the issue

IoBroker Admin v6.4.3
js-controller: 4.0.24
node.js c18.15.0
Platform: Proxmox (12Core 128Gb Ram) Debian VM (4x 1991Mhz / 16Gb Ram / 128Gb SSD)

![image](https://github.com/ioBroker/ioBroker/assets/62553223/c259fd15-24e9-49b5-bdff-6e9940943d04)

**Comment by Apollon77** [comment]
ENOMEM ... ... ... that sounds like you run out of memory on your system and so no new proceses could be started becausealso happens when he tried to start an adapter.

Check free mem and make sure to not run more adapters and other processes then your system has available RAM.
