### ISSUE TITLE
Delete / Check Logfile Error (Windows)

### ISSUE THREAD

**Issue by YARD2** [ioBroker/ioBroker#454]
Hello,
I found that older Logfiles can not be deleted.
Only way is to stop IOBroker and remove the logs:
Error Message e.g.

host.HomeServer | 2023-06-12 15:16:38.106 | error | cannot  check file: C:\ioBroker\log\iobroker.2023-06-04.log - EPERM: operation  not permitted, lstat 'C:\ioBroker\log\iobroker.2023-06-04.log'

host.HomeServer | 2023-06-12 15:16:38.105 | error | cannot  check file: C:\ioBroker\log\iobroker.2023-05-28.log - EPERM: operation  not permitted, lstat 'C:\ioBroker\log\iobroker.2023-05-28.log'

host.HomeServer | 2023-06-12 15:16:38.103 | error | cannot  check file: C:\ioBroker\log\iobroker.2023-05-24.log - EPERM: operation  not permitted, lstat 'C:\ioBroker\log\iobroker.2023-05-24.log'

Curious is, that the logs between these are deleted.
There is no permission problem.

**Comment by Apollon77** [comment]
Yes this is a known issue on Windows sometimes. We never found out why windows prevent this sometimes and which exact permission issue happens here. if you can check on your side please do so ..

**Comment by Apollon77** [comment]
duplicate https://github.com/ioBroker/ioBroker.js-controller/issues/1637

**Comment by leopard3330** [comment]
Same bug, But IOB will remove the owner from the file, and than only restart windows can solve it

**Comment by Apollon77** [comment]
Please comment this to the referenced issue above becaue this here is a dulocate of the other one
