### ISSUE TITLE
Command `iob node-update`, like `iob fix`, that starts node_update.sh shell script

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker#458]
- `iob stop`
- `iob backup`
- install suggested node.js 
    `curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - `
    `sudo apt-get install -y nodejs`
- check that `/usr/bin/node` and `/usr/bin/nodejs` are valid and if required fix them!
- `iob start`
![image](https://github.com/ioBroker/ioBroker/assets/4582016/463665bb-59c0-427f-8875-e1b6592ef048)

**Comment by Grothesk242** [comment]
The nodesource installer skript is obsoleted. But I have a replacement at hand. Is somebody else already working on it or shall I convert my code to a node-update function?

**Comment by Apollon77** [comment]
> The nodesource installer skript is obsoleted.

Why? It sis working fine and ideal in my eyes.

**Comment by Apollon77** [comment]
Aahhhh ok now I see ...

@Grothesk242 I think nooen works on it. so ig you caould adjust #464 into an install/update function that can ube used in both caes would be cool. thank you

**Comment by buanet** [comment]
@Apollon77 @Grothesk242 Whats wrong with the installer script? Any source for that info? Anything I need to know? :) Thx.

Regards,
André

**Comment by Apollon77** [comment]
Check the nodesourece page. Seems to be gone ...

**Comment by Grothesk242** [comment]
I did code some kind of 'iob node-updater'. I don't know how to create a PR for a new file in iobroker. See 
https://github.com/Grothesk242/iob_diag/blob/main/iob_node_update

@buanet The nodesource-Installationscripts are deprecated now and they did change  the setup of their repository. Updates will only be published via the new repository.

**Comment by Grothesk242** [comment]
https://github.com/nodesource/distributions

"Installation Scripts: The installation scripts setup_XX.x are no longer supported and are not needed anymore, as the installation process is straightforward for any RPM and DEB distro."

**Comment by buanet** [comment]
Thank you. My quick search (I'm only mobile at the moment) was not successful, but now I got the right site. :) Will look into this as it will also affect the Docker image.

**Comment by Grothesk242** [comment]
> so ig you caould adjust #464 into an install/update function that can ube used in both caes would be cool.

I'd prefer to have it separated in the installer and a 'iob node-fix' skript. Makes it much easier to maintain.

**Comment by Grothesk242** [comment]
Code can be pulled in from 
https://github.com/Grothesk242/iob_diag/blob/main/iob_node_update
My tests did not show big technical issues. The output could be a little bit nicer, I have to admit.

**Comment by Grothesk242** [comment]
https://github.com/ioBroker/ioBroker/pull/465
Not sure if the PR is correct... :-) 
Struggeling with github atm...
