### ISSUE TITLE
Quickest way to write object to object on change

### ISSUE THREAD

**Issue by MartiMan79** [ioBroker/ioBroker#459]
Hi all,

I am looking for a way to update multiple tags between 2 adapter instances (hmip and S7) so I can control everything from WINCC Unified Runtime.

Sadly I'm a PLC guy so I would start with "FOR i := 1 TO 99 DO" and update loads of arrays at once. 🤣 

Wish it was as simple here too, or am I missing an ingenious idea?
Hopefully someone has one as I would not like to update 50 tags through Blockly 😞

Thanks in advance!

![Screenshot 2023-07-30 181940](https://github.com/ioBroker/ioBroker/assets/56831581/fd3ca251-638f-45d8-99b0-4bf941237003)

**Comment by Apollon77** [comment]
I think better post this question in the ioBroker Forum Scripting area.... noone will see it here because GitHub is mainly used for Issues and Feature requests.
