### ISSUE TITLE
Values wrong defined

### ISSUE THREAD

**Issue by flapman** [ioBroker/ioBroker#460]
`<html>
<body>

info.0 | 2023-08-05 10:30:54.098 | info | State value to set for "info.0.sysinfo.cpu.info.cache-l3" has to be type "number" but received type "string"
-- | -- | -- | --
info.0 | 2023-08-05 10:30:54.093 | info | State value to set for "info.0.sysinfo.cpu.info.cache-l2" has to be type "number" but received type "string"
info.0 | 2023-08-05 10:30:54.089 | info | State value to set for "info.0.sysinfo.cpu.info.cache-l1i" has to be type "number" but received type "string"
info.0 | 2023-08-05 10:30:54.036 | info | State value to set for "info.0.sysinfo.cpu.info.cache-l1d" has to be type "number" but received type "string"
info.0 | 2023-08-05 10:30:53.946 | info | State value to set for "info.0.sysinfo.cpu.info.speed" has to be type "string" but received type "number"

</body>
</html>`

**Comment by Apollon77** [comment]
info adapter is deprecated
