### ISSUE TITLE
Nodejs has changed its repository ==> adapt installer script

### ISSUE THREAD

**Issue by winnyschuster** [ioBroker/ioBroker#462]
starting August, 30th, node has changed its repository, thus users that used to install node with `setup_$version.x` scripts won't receive any future updates. Because of this iobroker install.sh should reflect these changes asap

**A PR is in development and will be provided soon**

more information see: https://github.com/nodesource/distributions#new-update-%EF%B8%8F

**Comment by Grothesk242** [comment]
https://github.com/ioBroker/ioBroker/pull/464

**Comment by foxriver76** [comment]
Can be closed @Apollon77?
