### ISSUE TITLE
Problem in Verbindung mit Wireguard

### ISSUE THREAD

**Issue by ThomasTom86** [ioBroker/ioBroker#467]
Habe den iobroker auf meinem Server laufen und wollte für den Fernzugriff wireguard installieren. Die Wireguard Installation hat funktioniert und der Fernzugriff ins Netzwerk war möglich. Leider war dann der Zugriff auf die Web Oberfläche auf den Iobroker per ip:8081 nicht mehr möglich. Gelaufen ist er noch aber nicht alle Adapter. Habe alles mögliche Versucht zum Wiederherstellen, leider hat gar nichts geholfen. Am Schluss blieb mir nur meine Backup SSD übrig. 

Hab mir gedacht, dass ich eventuell irgendwas bei der Installation falsche gemacht habe. Zum Testen hab ich dann einen Raspi (192.168.1.244)hergenommen. Wireguard (192.168.100.1) installiert und mit Iphone als Client (192.168.100.2) getestet. Danach die Installation vom iobroker. Installation läuft durch und am Schluss kommt die Meldung (Bild) wie der iobroker erreichbar ist. Dort stehen 2 ips drinnen. Mit keiner der beiden ist der iobroker im Browser aufrufbar. Laufen tut er. 

Hat jemand eine Idee was ich das machen kann? Liegt es am Iobroker od. an wireguard? 

Danke![image](https://github.com/ioBroker/ioBroker/assets/75570143/2096351d-e236-49af-9f11-2497431c3f22)

**Comment by Apollon77** [comment]
@Grothesk242 Any idea? :-)

@ThomasTom86 Was sagt das ioBroker log?

**Comment by Apollon77** [comment]
Ich denke das ein netzwerkthema ... ich habe keine AHnung wie das richtig für Wireguard aufgesetzt werden muss das das tut. Admin sollte im Default auf 0.0.0.0 binden. Wäre für mich eher ein Support Thema im Forum

**Comment by ThomasTom86** [comment]
Habs im Forum gepostet. Danke

**Comment by Grothesk242** [comment]
> @Grothesk242 Any idea? :-)

Nein, keine idea. Ich verwende bei tailscale. Das ist so einfach aufzusetzen, das kann sogar ich.

**Comment by Apollon77** [comment]
@ThomasTom86 Hast DU bitte mal den Link?

**Comment by ThomasTom86** [comment]
Bin auf schon drauf gekommen, es liegt an der firewall. Wenn man die Ports frei gibt funktioniert's. 
sudo ufw disable od. 
sudo ufw allow 8081/
