### ISSUE TITLE
Support of systemd

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker#47]
detect systemd by "/etc/systemd/"

http://nodesource.com/blog/running-your-node-js-app-with-systemd-part-1/

create sudo nano `/lib/systemd/system/iobroker.service`

with

```
[Unit]
Description=ioBroker Server
Documentation=http://iobroker.net
After=network.target

[Service]
Type=simple
User=iobroker or root
ExecStart=/usr/bin/node /opt/iobroker/node_modules/iobroker.js-controller/controller.js
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

User iobroker must be created by installation (oder root benutzen)

```
sudo systemctl daemon-reload
sudo systemtl enable iobroker
sudo systemctl start iobroker
```

Notice: iobroker start must support systemd and call this command

**Comment by AlCalzone** [comment]
> User iobroker must be created by installation (oder root benutzen)

Does this mean we can run ioBroker as non-root and leave out the `sudo` stuff from installations (except zwave)? As-is this causes more access right issues than it solves.

**Comment by Apollon77** [comment]
You can basically already now ... but the problems will be the same as currently too ... some module  installations will have problems and things like „use serialport as root User without special preparations“ still appear. :-(

**Comment by AlCalzone** [comment]
> serialport as root User

Thats probably the main exception we need to support. We should be able to solve that by running the adapter process as root somehow.

For me at least, most installations must be run with `sudo npm install ...` and then the weird stuff begins.

**Comment by GermanBluefox** [comment]
No. It is not normal.
This file should be created automatically. Where did you get it?
Anyway. Change
```User=iobroker or root```
to
```User=root```

пн, 15 окт. 2018 г. в 11:36, Boris <notifications@github.com>:

**Comment by dr3do** [comment]
> Where did you get it?

It came with the installation of ioBroker via this method http://www.iobroker.net/docu/?page_id=5106&lang=de, IIRC.

> Change…

Thanx! It did the trick.
