### ISSUE TITLE
Error gcc-c+ with iob fix

### ISSUE THREAD

**Issue by Wildbill-Z** [ioBroker/ioBroker#479]
After updating Nodejs form 18.18.0 to 18.18.1 I did a

iob fix 
as I always do. And ther I saw an error for the first time:

E: Paket gcc-c+ kann nicht gefunden werden.
E. Mittels regulärem Ausdruck 》gcc-c+《 konnte kein Paket gefunden werden.
Installed gcc-c++
Script went on and all is fine, but I wonder if I just not looked at it in the past or if the error is new to my system.
Running Debian Bookworm in an VM under Proxmox.

[HERE](https://forum.iobroker.net/topic/69038/iobroker-fix) in the forum is a post which describes it more.

**Comment by Apollon77** [comment]
fixed in update today
