### ISSUE TITLE
iob nodejs-update wartet nicht auf Eingaben

### ISSUE THREAD

**Issue by Diet1976** [ioBroker/ioBroker#481]
Hallo zusammen,
wenn ich iob nodejs-update starte, habe ich keine Chance, auf y oder n im Skript zu drücken, weil das Skript einfach bis zum Schluss durchläuft ohne auf eine Eingabe zu warten.
Ist das nur bei mir so und kann ich da etwas dran ändern?

LG, Dietmar

**Comment by Apollon77** [comment]
Bitte mehr Infos zum system. Weiterhin zur fixer verison ? Oder einfach nochmal "Iob fix" ausführen - passiert es dann immer noch?

**Comment by Diet1976** [comment]
Super Tipp mit dem iob fix. Gefühlt hatte ich das schon gemacht aber jetzt
hat es geklappt!
Danke auch für das coole Update-Skript, gefühlt war das vorher echt immer
manuelles Gebastel, wenn sich die Nodejs-Version wieder mal geändert hat.

LG

Am Di., 17. Okt. 2023 um 09:27 Uhr schrieb Ingo Fischer <
***@***.***>:

**Comment by Apollon77** [comment]
Das neue ist aber nur für major nodejs upgrades!
