### ISSUE TITLE
SNMP Bringt bei Installation folgenden Fehler

### ISSUE THREAD

**Issue by Wastl49** [ioBroker/ioBroker#497]
snmp has an invalid jsonConfig: [{"instancePath":"/items/authorization/items/authSets/items/4","schemaPath":"#/definitions/passwordProps/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"attr"},"message":"must NOT have additional properties"},{"instancePath":"/items/authorization","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"}]

**Comment by Apollon77** [comment]
Please craete this issue in the repository of the relevant Adapter
