### ISSUE TITLE
Adater Installation aus Git schlägt fehl

### ISSUE THREAD

**Issue by tomtom2021** [ioBroker/ioBroker#505]
Hallo, ich bin neu hier im Forum vll kann mir jemand helfen. Ich versuche den Adater [Daly-Swift](https://github.com/christophhagen/Daly-Swift) von Git zu installieren und bekomme diese Fehlermeldung:
$ iobroker url .package(url: "https://github.com/christophhagen/Daly-Swift", from: "0.9.0") --host thomas-desktop --debug
install .package(url:
NPM version: 10.2.3Installing .package(url:... (System call)
npm ERR! path /opt/iobroker/.package(url:/package.json
npm ERR! errno -2
npm ERR! A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-01-18T13_13_41_034Z-debug-0.log
npm ERR! code ENOENTnpm ERR! syscall opennpm ERR! path /opt/iobroker/.package(url:/package.jsonnpm ERR! errno -2npm ERR! enoent ENOENT: no such file or directory, open '/opt/iobroker/.package(url:/package.json'npm ERR! enoent This is related to npm not being able to find a file.npm ERR! enoent npm ERR! A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-01-18T13_13_41_034Z-debug-0.log
host.thomas-desktop Cannot install .package(url:: 254
ERROR: Process exited with code 25

**Comment by Apollon77** [comment]
Das ist kein ioBroker Adapter
