### ISSUE TITLE
Opentherm adapter

### ISSUE THREAD

**Issue by renne** [ioBroker/ioBroker#52]
Hi,

I suggest an [OpenTherm](https://www.opentherm.eu/) adapter for the [OpenTherm protocol](http://www.domoticaforum.eu/uploaded/Ard%20M/Opentherm%20Protocol%20v2-2.pdf) to control heating systems.
[opentherm2mqtt](https://github.com/githubcdr/opentherm2mqtt) is a javascript implementation of the [OpenTherm protocol](http://www.domoticaforum.eu/uploaded/Ard%20M/Opentherm%20Protocol%20v2-2.pdf).

**Comment by Apollon77** [comment]
Thank you for your post.
Great idea, Best is to post it into ioBroker Forum to maybe find interested developers to develop it.

Here on GithHub we only  handle effective issues in this case for the ioBroker initial installation procedure and not for ioBroker at all.
