### ISSUE TITLE
Horizontal scrollen nicht mögliche

### ISSUE THREAD

**Issue by ryto1** [ioBroker/ioBroker#54]
- in Skripte kann in der "Baumspalte" horizontal nicht gescrollt werden
- im Viseditor ist scrollen horizontal ebenfalls nicht möglich (kein Balken)
mit Crom und Firefox versucht

**Comment by GermanBluefox** [comment]
Bitte für die entsprechende Module die richtige github repos verwenden.

Das hier ist sehr allgemein und keine schaut hier an.

вт, 8 мая 2018 г., 14:05 ryto1 <notifications@github.com>:
