### ISSUE TITLE
Forced data transfer

### ISSUE THREAD

**Issue by OgreTransporter** [ioBroker/ioBroker#56]
The first time you call up the web interface to configure ioBroker after installation, the assistant will force you to agree to the data transfer. There is a hint that the transmission can be deactivated later. This is a violation of the GDPR, as this data are not necessary for the operation of ioBroker.

**Comment by GermanBluefox** [comment]
If I don't know how many users uses the iobroker, I don't know on which parts of the software I should concentrate my development. If I will implement unimportant things the number of users will low. If the number of users will low, I will not work on this software anymore. If I will not work on it, I cannot close security or performance issues . If the software has security issue, it cannot be run by end users. That means, that statistics is very important for the operation of iobroker.

**Comment by GermanBluefox** [comment]
Zitat:
Die bayerische Aufsichtsbehörde äußert sich

Hierzu hat das LDA Bayern vor kurzem eine in unseren Augen interessante
Auslegung veröffentlicht (Zitat):

    Daraus dürfte folgen, dass bei „kostenlosen“ Dienstleistungsangeboten,
die die Nutzer mit der Zustimmung für eine werbliche Nutzung ihrer Daten
„bezahlen“ (z. B. kostenloser E-Mail-Account gegen Zustimmung für
Newsletter-Zusendung als „Gegenfinanzierung“), diese vertraglich
ausbedungene Gegenleistung des Nutzers bei Vertragsabschluss klar
dargestellt werden muss. Raum oder Notwendigkeit für eine Einwilligung
besteht dann nicht mehr.

Das LDA Bayern vertritt also den Standpunkt, dass im Rahmen der
Interessenabwägung bei kostenlosen Dienstleistungen durchaus angenommen
werden kann, dass der Empfang von Werbung als Gegenleistung eines Vertrags
angesehen werden kann. Wir sehen diese Ansicht durchaus als im Sinne der
Nutzer, denn ohne die Möglichkeit der Werbung dürfte das Angebot an
kostenlosen Dienstleistungen stark abnehmen. Wichtig ist, wie auch das LDA
Bayern schreibt, dass der Nutzer in den Vertragsbedingungen über die
Nutzung für Werbung aufgeklärt werden muss. Werbung wird damit sozusagen
Produktbestandteil.

чт, 7 июн. 2018 г., 11:53 OgreTransporter <notifications@github.com>:

**Comment by GermanBluefox** [comment]
3. It is not personal information. GDPR coordinates only personal data. If
you can find out what the person sends the statistics (sex, address, name,
billing info) please let me know. I will fix it.

Assuming there is no city with only one citizen.

чт, 7 июн. 2018 г., 16:02 Smart Home - ioBroker <dogafox@googlemail.com>:

**Comment by BuZZy1337** [comment]
There is absolutely no way to get any kind of personal data out of the transmitted statistic..

**Comment by Apollon77** [comment]
Very impoertant for the third comment above about "getting advertising": ioBroker WILL NOT send out any advertising mails! (and even is not able with these collected statistic data)

**Comment by OgreTransporter** [comment]
It has nothing to do with advertising. When I install ioBroker local, the transfer of statistical data is not necessary for the operation of the local installation. The data may be interesting for development, but not necessary for operation. The GDPR only requires data to be collected that is absolutely necessary for operation. All other data requires the **voluntary** consent of the end user. A forced approval during setup is not permitted.

The ticket is intended as an indication. Personally, I don't care what ioBroker does anymore, because the system doesn't work properly I won't use it productively.

**Comment by GermanBluefox** [comment]
Thank you for the indication of possible problem and we checked the issue and found out, that everything is OK. No personal data will be collected and GDPR is about PERSONAL data.

>Personally, I don't care what ioBroker does anymore, because the system doesn't work properly I won't use it productively.

It would help if you will show us the problem. It will help nobody to say: you product is awful without details.

**Comment by OgreTransporter** [comment]
> It would help if you will show us the problem. It will help nobody to say: you product is awful without details.

There are several things that prevent me from using ioBroker.

1. As already reported, the adapter plugin list retrieval does not work (Ubuntu 18.04 LTS). I installed some plugins manually to test the system.
2. About ~40 MB RAM per plugin instance is a bit much. My target system should run on a Raspberry Pi 1 B+ (512 MB). For example, an MQTT broker can be set up in a few KB (see NodeMCU).
3. The control options are very limited. Using more complex algorithms is a considerable effort.

**Comment by OgreTransporter** [comment]
1. Maybe ioBroker is not working under Ubuntu 18.04
```
host.Ubuntu-Desktop | 2018-06-11 10:05:14.577 | warn | warning: Cannot read "http://download.iobroker.net/sources-dist.json"
-- | -- | -- | --
```

```
ubuntu@Ubuntu-Desktop:~$ date
Mo 11. Jun 10:08:47 CEST 2018
ubuntu@Ubuntu-Desktop:~$ sudo iobroker update
Used repository: default
Cannot download json from http://download.iobroker.net/sources-dist.json. Error: Error: connect ECONNREFUSED 79.143.182.215:80
update done
ubuntu@Ubuntu-Desktop:~$ 
```
2. The idea is to use one Rasperry Pi to save energy. Instead of several Rasperry Pis I can also use a large computer. I'll have a look at CppMicroServices (based on OSGi) - which also enables a modular system.

3. Yes, I've a watering device for my plants. The box has multiple sensors (insolation, temperature, humidity (air), soil moisture). I combine that data with the weather forecast, sunrise, sunset and a model of the water consumption of my plants. I have a control algorithm that is using all that data to perfect water my plants. It also calculates total water consumption. The controller is built in Simulink and can be exported as C/C++ code.

**Comment by Apollon77** [comment]
1.) No incompatibility to ubuntu 18.04 was reported so far and in fact nodejs is encapsulating all the network functions. Can you try getting the file directly via curl on this computer or also from an other computer in the same network/other network?!

2/3) ioBroker is based on nodejs and so JavaScript and yes compared to C/C++ this introduces some overhead. If you have your system as a binary you could execute the logic vis exec to handle the data - or reimplement as JavaScript. With The JavaScript-adapter you have full scripting capabilities for as complex scripts and tasks as you like :-)

But in fact if you seatch for a system where you can reuse your already existing C/C++ stuff then ioBroker may not be the ideal choice. But this is a architectural decision.

**Comment by OgreTransporter** [comment]
@Homoran https://github.com/ioBroker/ioBroker.admin/issues/276

**Comment by GermanBluefox** [comment]
@OgreTransporter Thank you for your feedback. All points (except "repo not available") are known and it was the deliberate decision for RAM and no CPP. 
There are too many other advantages of Node.JS in compare of CPP.

**Comment by jpicht** [comment]
Just FYI @GermanBluefox - I was going to give ioBroker a test, but the forced consent, then one or two steps later it asks for my geo-location - that really killed it for me.
Just so you understand, I don't think that the location data is actually transmitted, but there's a sour taste ("Geschmäckle") with this forced data transmission consent in combination with sensitive data.

I would suggest to change the logic to being able to chose to consent now, or to "ask me later". This will allow the user to build up trust in the system before actually consenting to data transmission.

I understand that the data collected is valuable and forcing consent makes is more likely that you actually get data. But just plain forcing it on, so you get at least the install ping, is really a terrible solution IMO, because you'll never know if a single ping is just a quick test run, or somebody immediately turning off telemetry.

Asking the user later will create the added benefit, that you'll only get data from users who actually used it until "later".
