### ISSUE TITLE
Moving to another script instance - objects won't visible

### ISSUE THREAD

**Issue by mister-extra** [ioBroker/ioBroker#57]
as described at the iobroker forum ( https://forum.iobroker.net/viewtopic.php?f=22&t=14386 ) .

please help,
after changing the instance of a script (in iobroker admin) the script-object won't appear under the chosen instance. the script object stays under the old instance. therefore it isn't possible to stop or start the script with another script.
the script is working - only the object of the script is missing at the right place.

ändert man die instanz eines javascripts wird das eigentliche script-object nicht unter der neuen instanz sichtbar. das script-object bleibt unter der alten instanz sichtbar - ist aber nicht steuerbar (script selbst funktioniert). somit ist es unmöglich ein verschobenes script mit einem anderen script zu steuern

**Comment by GermanBluefox** [comment]
Duplicate to https://github.com/ioBroker/ioBroker.javascript/issues/128

**Comment by mister-extra** [comment]
Dear bluefox, Sorry for the duplicate - but nobody reacts on this issue - 
I do not even know if the problem was recognized everywhere or it is my iobroker problem ? Is there any chance to get some feedback ?

**Comment by GermanBluefox** [comment]
We recognised the problem, but priorities are now not at this adapter

пт, 22 июн. 2018 г., 8:46 mister-extra <notifications@github.com>:

**Comment by mister-extra** [comment]
sorry - I didn't want to annoy you - thanx for info
