### ISSUE TITLE
View Explorer Fenster

### ISSUE THREAD

**Issue by 4Josh** [ioBroker/ioBroker#58]
Hallo,

ich würde es gut finden wenn es ein Explorer Fenster mit Ornderoption für die View im Vis-Editor geben würde. Bei vielen Views wird es dann doch recht unübersichtlich.

Gruß 4Josh

**Comment by Apollon77** [comment]
Please reopen this in the correct Github repo: https://github.com/ioBroker/ioBroker.vis
