### ISSUE TITLE
(Some) Icons do not appear in the Objects/Zigbee adapter

### ISSUE THREAD

**Issue by tanelkoth** [ioBroker/ioBroker#586]
Hello,

I have observed the following odd behaviour: Some icons do appear in the objects list and some do not. Although the icon-files do exists and are readable. Looking at the icon-files in the browser or other program let them see properly. When I change the icon definition in the code for an icon that is displayed, it displays as well. When I change it back it is replaced with the 'broken icon' icon. What is happening here? Why do some icons show up and others do not?

Example pictures:
![icons](https://github.com/user-attachments/assets/3dcbd96d-0387-47ab-8510-46e944e31f72)

I hope someone can help to solve this mysterious behaviour.
Regards,
erwin

**Comment by Erwin40** [comment]
Bitte mal ein Upload im ZegBee Adapter machen.
Dann sind die Icons vorhanden.
Der Upload muss jedes Mal gemacht werden, wenn ein neuer Geräte-Typ hinzugefügt wurde, den der ZegBee Adapter noch nicht kannte.

**Comment by tanelkoth** [comment]
Danke schön für die Antwort. Können Sie mir bitte sagen in welchen Directory der Upload gemacht werden muß? 
Ich habe zwei Directories gefunden wo die images stehen:

1) /opt/iobroker/node_modules/iobroker.zigbee/admin/img/
2) /opt/iobroker/iobroker-data/files/zigbee.admin/img/

Einen Upload in diesen beiden Directories hat nicht geholfen. Gibt es noch einen andere Directory?

Vielen Dank für die Hilfe.

**Comment by Erwin40** [comment]
Nee :-)
In der Admin Oberfläche vom ioBroker, links auf Adapter gehen und über den Stern auf "installierte Adapter" eingrenzen.
![grafik](https://github.com/user-attachments/assets/d91ea8fa-da87-45e3-b84e-09428fcdb6b0)

Dann beim ZigBee Adapter oben rechts die 3 Punkte anklicken und unten auf Upload klicken.
![grafik](https://github.com/user-attachments/assets/a2d20d93-fbd3-4a15-8fae-baa1e9678814)

Oder per SSH-Zugriff direkt auf dem RaspberryPi:
iob upload zigbee

**Comment by Erwin40** [comment]
Zu diesen Verzeichnisse:
/opt/iobroker/node_modules/iobroker.zigbee/admin/img/
/opt/iobroker/iobroker-data/files/zigbee.admin/img/

Hast du dort etwas geändert?
Dort hat nur der iobroker was zu suchen oder ändern.
Und eigentlich sollten dir da auch die entspr. Berechtigungen fehlen.

**Comment by tanelkoth** [comment]
Uebrigens: Im Zigbee dashboard wird wohl der richtige Abbildung gefunden und genützt. Sehe vorbild:

![Knipsel-02](https://github.com/user-attachments/assets/dea5f168-6674-4a14-8d87-fca4e59a13a6)

**Comment by tanelkoth** [comment]
After a restart the icons do appear. The upload probably has worked!
Thanks very much for the help. It is much appreciated.
Regards,
erwin
