### ISSUE TITLE
Add ioBroker logo to the TypeScript website?

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker#60]
http://www.typescriptlang.org/community/friends.html

As the JS adapter supports TypeScript I think we could add our logo there. Thoughts?

**Comment by GermanBluefox** [comment]
Yes, we can try :) Will you do that?

вт, 24 июл. 2018 г. в 14:16, AlCalzone <notifications@github.com>:

**Comment by AlCalzone** [comment]
Ping @GermanBluefox

**Comment by GermanBluefox** [comment]
https://github.com/ioBroker/awesome-iobroker/blob/master/images/awesome-iobroker.svg

**Comment by AlCalzone** [comment]
Done: https://github.com/Microsoft/TypeScript/issues/26249

**Comment by GermanBluefox** [comment]
@AlCalzone 
iobroker.com => iobroker.net !!!

**Comment by AlCalzone** [comment]
Fixed
