### ISSUE TITLE
Schriftfarbe, -größe, Hintergrundfarbe

### ISSUE THREAD

**Issue by mhandschuher** [ioBroker/ioBroker#61]
Die graue Schrift auf grauem Hintergrund ist nur sehr schwer lesbar und die Schrift außerdem im Verhältnis zu den Eingabefeldern zu klein.

**Comment by Apollon77** [comment]
Bitte mehr Kontext ... wo??? Screenshot?

**Comment by mhandschuher** [comment]
Das betrifft die gesamte Oberfläche des aktuellen ioBroker (Einstellungen bei den Instanzen und Objekten). Weiß leider nicht, wie ich hier einen Screenshot einfügen kann (bin komplett neu hier). Alle Eingabemasken haben einen hellgrauen Hintergrund und die Beschreibungstexte bei den Eingabefeldern sind ebenfalls grau (nur etwas dunkler) und außerdem vom Schriftgrad wesentlich kleiner wie der Font in den Eingabefeldern.

**Comment by Apollon77** [comment]
Ahhhh. ... darf ich dich bitten das als issue beim repository vom iobroker Admin anzulegen ?! Danke
