### ISSUE TITLE
Ideas for future improvements of the installer

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker#67]
- [x] Installer script or binary for Windows (Stabilostick might have something here)
- [x] Automatic installation of the correct Node version
- [x] Automatic installation of the correct npm version. On windows this requires copying the npm folder from `%APPDATA%\npm\node_modules\npm` to `<location of nodejs>\node_modules\npm`. The location can be found using `where node`.
- [x] Linux only: Preventing installation with root rights or (alternatively) executing the npm commands as the newly-created iobroker user

**Comment by AlCalzone** [comment]
The npm permissions problem has been fixed with #99

**Comment by GermanBluefox** [comment]
Close?

**Comment by AlCalzone** [comment]
The first 3 points are not solved yet.

**Comment by Apollon77** [comment]
I would be ok with it ... the WIndows topic is handled by Stabilostick at the moment with the otehr two points for WIndows. For Linux I would stay as we are ... but my opinion

**Comment by AlCalzone** [comment]
Well, this topic is not limited to Linux

**Comment by AlCalzone** [comment]
Fixed I think
@Apollon77 @Stabilostick ?

**Comment by Apollon77** [comment]
Close for me

**Comment by Stabilostick** [comment]
Too late, but ok for me, too.

**Comment by Apollon77** [comment]
;-)
