### ISSUE TITLE
Redirect to shorten installer.sh location

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker#71]
@GermanBluefox 

We want to have 

https://raw.githubusercontent.com/ioBroker/ioBroker/stable-installer/installer.sh

available when calling

https://iobroker.net/install-linux.sh

Can you please setup a redirect/rewrite rule accordingly?!

Thank you

**Comment by Apollon77** [comment]
Status: BF had set it up with a different port, but we think that we will have problems with this. We want standard SSL if possible

AND: We also need it for the fixer-skript in the meantime

**Comment by AlCalzone** [comment]
Fixed I think? @Apollon77

**Comment by Apollon77** [comment]
yes
