### ISSUE TITLE
How to enable debug?

### ISSUE THREAD

**Issue by misterx** [ioBroker/ioBroker#72]
Sometimes i receive this warning `iobroker_1  | (node:1) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated`. How to enable debug mode that can hepls me find file with this warning?

**Comment by Apollon77** [comment]
You need to find out which process throws this error. Do you know that? Is it an adapter or js-controller? Which nodejs version?

**Comment by misterx** [comment]
@Apollon77 I wanna find but i can't ;) I don't know which is part of iobroker raise this warning. `Node.js: v8.12.0 , NPM: 6.4.1`

**Comment by misterx** [comment]
@Apollon77 This error is in console not in error log. I'm runnig iobroker with docker.

**Comment by Apollon77** [comment]
Problem is that also debug log will not reveal more information. Is it reproducable? Then try to run only one adapter, see if it happends, then start to enable more and more one after the other

**Comment by Apollon77** [comment]
And to the same times no corresponding errors in iobroker logfile?

**Comment by misterx** [comment]
@Apollon77 iobroker logfile is clear, this warning appears only in stdout. So, i've disabled all adapters except admin and still receive this warning at startup.

**Comment by misterx** [comment]
@Apollon77 When i restart admin adapter this error does not appear again. I think this is iobroker or iobroker-controller warning. Can i run controller in debug mode?

**Comment by misterx** [comment]
I've tried to run `node --trace-warnings node_modules/iobroker.js-controller/controller.js start` but trace not show only warning.

**Comment by Apollon77** [comment]
debug mode will not help!
you need to start js-controller process with --throw-deprecation as additional parameter, then a stack trace should be shown in case of this error ... try that

**Comment by misterx** [comment]
i've tried the follow combinations:
```
node --trace-warnings --trace-deprecation node_modules/iobroker.js-controller/controller.js start
node --trace-warnings --trace-deprecation --throw-deprecation node_modules/iobroker.js-controller/controller.js start
node --throw-deprecation node_modules/iobroker.js-controller/controller.js start
```
So, nothing except warning, no trace. Looks like controller starts other process that raise this warning and omit this flags. I've tried to find answer in google and many peoples receive this warning when use fs.writeFile without third callback parameter. As example https://github.com/nodejs/node/issues/14770

**Comment by misterx** [comment]
I've found only one place where `writeFile `is incorrect, here https://github.com/ioBroker/ioBroker.js-controller/blob/9e98c259262287eae620d0bdbd07fb49c7134af1/controller.js#L1647

**Comment by Apollon77** [comment]
Try to change the file on your local installation and then you see if error is gone

**Comment by misterx** [comment]
@Apollon77 Looks like is not there

**Comment by misterx** [comment]
i've found deprecation stack by adding env variable `ENV NODE_OPTIONS --trace-warnings`.
Stack:
```
(node:1) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
    at makeCallback (fs.js:127:12)
    at Object.fs.unlink (fs.js:1049:14)
    at deleteOldBackupFiles (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemServer.js:326:24)
    at Timeout.saveState (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemServer.js:387:25)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
```

**Comment by misterx** [comment]
`fs.unlink` must have callback here https://github.com/ioBroker/ioBroker.js-controller/blob/1.4.1/lib/states/statesInMemServer.js#L326

**Comment by Apollon77** [comment]
I think more unlinkSync should be used ... ut the writeFile above is also such a candidate ((--> writeFileSync)

**Comment by misterx** [comment]
@Apollon77 Yes, in latest version this is fixed, but stable version 1.4.2

**Comment by Apollon77** [comment]
aahhhh ... latest means "Master"? Then it will come with 1.5.x ... and is now a "Known bug" in 1.4.2 
you could give 1.5.3 (on npm installable via js-controller@1.5.3 a try ... only some people had strange problems with SSL

**Comment by misterx** [comment]
Yes i mean master :-) I'll try ti use 1.5.3

**Comment by Apollon77** [comment]
I close here because fixed already
