### ISSUE TITLE
autostart not working --> iobroker.sh missing in new installation

### ISSUE THREAD

**Issue by wendy2702** [ioBroker/ioBroker#73]
Hi i just installed iobroker on the latest Raspian Stretch version and autostart is not working because iobroker.sh is missing at /etc/init.d

After i copied the file to etc/init.d/,  change file permissions and did a update-rc.d .... , autostart is working after reboot.

**Comment by Apollon77** [comment]
Kann es sein das die neuen Versionen jetzt systemd basiert sind? Dann sind Skripte unter /etc/init.d nicht mehr korrekt

**Comment by wendy2702** [comment]
Hi, eigentlich ist ab Debian Stretch systemd zuständig aber das funktioniert zumindest hier nicht.
Im Forum wird als Lösung auch immer der weg über init.d genannt.
Die Möglichkeit weiterhin init.d zu verwenden ist aber auch meiner Sicht nichts ungewöhnliches.

Fakt ist das der Autostart bei Neuinstallation unter Raspian Stretch Lite nicht funktioniert.
Leider komme ich nicht so problemlos an die neue Installation um jetzt systemd zu prüfen/kontrollieren.

Vielleicht mal einen PI schnorren und testen.

**Comment by wendy2702** [comment]
Das hier gefunden: https://github.com/ioBroker/ioBroker/issues/47

Sollte das Problem nicht eigentlich beseitigt sein und der Autostart mit systemd funktionieren?

Bei meiner neuen Installation nach dieser Anleitung http://www.iobroker.net/docu/?page_id=5106&lang=de 

fehlt die Datei allerdings:

cat /lib/systemd/system/iobroker.service
cat: /lib/systemd/system/iobroker.service: Datei oder Verzeichnis nicht gefunden

**Comment by Apollon77** [comment]
muss das nicht /usr/lib... sein?

**Comment by wendy2702** [comment]
Laut Debian Wiki ist es /etc/systemd/system 

https://wiki.debian.org/systemd

Das iobroker.service File das in Issue: #47 hier angelegt wird: /lib/systemd/system/ gibt es bei mir nicht:

Da Alphabetisch sortiert nur ein Auszug:

-rw-r--r--  1 root root  1737 Jun 13 22:20 getty@.service
-rw-r--r--  1 root root   342 Jun 13 22:20 getty-static.service
-rw-r--r--  1 root root   460 Jun 13 22:20 getty.target
drwxr-xr-x  2 root root  4096 Okt  9 13:38 getty.target.wants
-rw-r--r--  1 root root   558 Jun 13 22:20 graphical.target
drwxr-xr-x  2 root root  4096 Okt  9 13:38 graphical.target.wants
lrwxrwxrwx  1 root root     9 Jun 13 22:20 halt.service -> /dev/null
-rw-r--r--  1 root root   487 Jun 13 22:20 halt.target
drwxr-xr-x  2 root root  4096 Okt  9 13:47 halt.target.wants
-rw-r--r--  1 root root   274 Aug  9 14:39 hciuart.service
-rw-r--r--  1 root root   447 Jun 13 22:20 hibernate.target
lrwxrwxrwx  1 root root     9 Jun 13 22:20 hostname.service -> /dev/null
lrwxrwxrwx  1 root root     9 Jun 13 22:20 hwclock.service -> /dev/null
-rw-r--r--  1 root root   468 Jun 13 22:20 hybrid-sleep.target
-rw-r--r--  1 root root   552 Jan 10  2017 ifup@.service
-rw-r--r--  1 root root   630 Jun 13 22:20 initrd-cleanup.service
-rw-r--r--  1 root root   553 Jun 13 22:20 initrd-fs.target
-rw-r--r--  1 root root   790 Jun 13 22:20 initrd-parse-etc.service
-rw-r--r--  1 root root   521 Jun 13 22:20 initrd-root-device.target
-rw-r--r--  1 root root   526 Jun 13 22:20 initrd-root-fs.target
-rw-r--r--  1 root root   640 Jun 13 22:20 initrd-switch-root.service
-rw-r--r--  1 root root   714 Jun 13 22:20 initrd-switch-root.target
drwxr-xr-x  2 root root  4096 Okt  9 13:47 initrd-switch-root.target.wants
-rw-r--r--  1 root root   723 Jun 13 22:20 initrd.target
-rw-r--r--  1 root root   664 Jun 13 22:20 initrd-udevadm-cleanup-db.service
-rw-r--r--  1 root root   501 Jun 13 22:20 kexec.target
drwxr-xr-x  2 root root  4096 Okt  9 13:47 kexec.target.wants
-rw-r--r--  1 root root   287 Mai 19  2016 keyboard-setup.service
lrwxrwxrwx  1 root root     9 Jun 13 22:20 killprocs.service -> /dev/null
lrwxrwxrwx  1 root root    28 Jun 13 22:20 kmod.service -> systemd-modules-load.service
-rw-r--r--  1 root root   677 Jun 13 22:20 kmod-static-nodes.service
-rw-r--r--  1 root root   395 Jun 13 22:20 local-fs-pre.target
-rw-r--r--  1 root root   507 Jun 13 22:20 local-fs.target
drwxr-xr-x  2 root root  4096 Okt  9 13:38 local-fs.target.wants
-rw-r--r--  1 root root   405 Jun 13 22:20 machine.slice
lrwxrwxrwx  1 root root    28 Jun 13 22:20 module-init-tools.service -> systemd-modules-load.service
lrwxrwxrwx  1 root root     9 Jun 13 22:20 motd.service -> /dev/null

**Comment by Apollon77** [comment]
Please retry with new installer and reopen if still valid
