### ISSUE TITLE
Create a script that fixes permissions and autostart and stuff on existing installations

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker#87]
As discussed with @Apollon77 we should create a script that fixes existing installations to a certain degree or brings them up to par with the installations our new installer creates. Let's call it fixmyshit.sh :laughing: 

It should do the following:
- [ ] fix permission errors in `/opt/iobroker`
- [ ] set the permissions like the installer does (with default ACL)
- [ ] create a user iobroker
- [ ] setup autostart with systemd and run iobroker under the iobroker user
- [ ] add permissions for nodejs to access bluetooth, gpio and other ports so we don't need to run adapters with root permissions
- [ ] handle migration from init.d to systemd
- [ ] Install `sudo` if it is not installed
- [ ] Add user `iobroker` to the `sudoers`

Did I forget something?

**Comment by Apollon77** [comment]
We should also have this as a "shell script loaded from github" script so that we have better control over it.

Maybe: handle migration from init.d script to systemd somehow?

**Comment by AlCalzone** [comment]
Should be just like the linux installer, so `curl | bash` from github.

**Comment by Apollon77** [comment]
correct
