### ISSUE TITLE
system commands (stop/start/status/restart) not working after installation with new script

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker#91]
the current commands like ioBroker stop are not working anymore when the new install script has been used.
It looks like these commands do not recognize the systemctl is used now for the proces, this results in not working stop command and when ioBroker start is used the proces is not started with systemctl.

`xxx@iobroker_dev:/opt/iobroker$ iobroker status
iobroker is running
xxx@iobroker_dev:/opt/iobroker$ iobroker stop
iobroker controller daemon is not running
xxx@iobroker_dev:/opt/iobroker$ sudo iobroker stop
[sudo] password for rafal: 
iobroker controller daemon is not running
xxx@iobroker_dev:/opt/iobroker$ iobroker
Commands:
`

**Comment by Apollon77** [comment]
--> https://github.com/ioBroker/ioBroker.js-controller/issues/289
