### ISSUE TITLE
Which commands should iobroker be allowed to execute as `sudo`?

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker#96]
I want to allow the user `iobroker` to execute `sudo` passwordless. This would fix some problems with the current installation (e.g. zwave can be installed over the admin again). But we should limit the commands `iobroker` is allowed to execute (at least by default). I need your input to find all of them.

And how do we handle javascript `exec`? We cannot know in advance which commands users want to execute. Maybe add a flag somewhere (should NOT be accessible via the admin for security reasons) to allow all commands.

**Commands:**

* `apt`
* `apt-get`
* `arp-scan`
* `fping`
* `make`
* `ping`
* `setcap`

**Comment by AlCalzone** [comment]
**From zwave:**
* `apt-get install` -> Or should we start handling this from inside js-controller?
* `make`

**Comment by Apollon77** [comment]
if you allow make then apt-getinstall is the same :-)
I would add functions like **ping, fping, arp-scan** and such that needs root to work

**Comment by AlCalzone** [comment]
Btw, we need the full executable path

**Comment by Apollon77** [comment]
von dem einen Forum Thread: moun umount, vllt noch setfacl

**Comment by AlCalzone** [comment]
iobroker sollte nach Update des Installers nicht mehr als Root ausgeführt werden. `systemctl` ist ok, `mount/umount` ist schon eingebaut

**Comment by simatec** [comment]
Für backitup wäre wie ich gerdae festgestellt habe auch noch "touch" und/oder "echo" gut

**Comment by AlCalzone** [comment]
Es geht hier nur um die befehle die sudo benötigen. Echo wird definitiv kein sudo benötigen. Was ist mit touch?

**Comment by simatec** [comment]
Mit touch schreibt backitup beim stoppen aktuell eine temporäre Datei, die defininiert, wie gestoppt wurde, damit beim Neustart wieder die gleiche Methode verwendet wird. Im Prinzip bräuchte touch dafür kein sudo, da in das Verzeichnis von backitup geschrieben wird und dort der User iobroker ja alle Rechte hat

**Comment by ltsalvatore** [comment]
regarding amazon-dash installation:
https://forum.iobroker.net/viewtopic.php?p=221120#p221120

**Comment by grimneko** [comment]
If you work with a unpriviliged user on FreeBSD, add to the list "pkg" (the counterpart to apt/apt-get on linux).

**Comment by frankjoke** [comment]
On top of the mentioned ones I use in my adapters the following tools which require root access:
dhcpdump, kill, l2ping, hcitool.

Some npm packages require also root, will find out on testing which ones I may need!
p.s.: Is a flag planned in the admin-instances to or in the config-json to run individual adapter completely in root?

**Comment by AlCalzone** [comment]
> Is a flag planned in the admin-instances to or in the config-json to run individual adapter completely in root?

We're thinking about it. Also configuring the commands on a per-adapter basis would make sense.

**Comment by schniddsel** [comment]
Would it be possible that iobroker is allowed to open port 80? Newer Alexas just listen on port 80 detecting devices. I tried some workarounds on developing my adapter, but nothing seems to work. I switched from OpenHab to iobroker, because I'm not in the mood to learn Java... But sadly not being able to emulate a full compatible hue bridge, just because I have no Access to port 80 let me think about switching back again. I know i can build this up for me using iptables e.g. But i want to make the adapter accessable for everyone. And some endusers may not now how to set up port 80.

**Comment by AlCalzone** [comment]
I think it is already allowed (if your installation was made with one of the newer installers and/or fixer scripts).
==> https://github.com/ioBroker/ioBroker/blob/master/installer.sh#L359
`cap_net_bind_service` allows binding ports < 1024.

**Comment by AlCalzone** [comment]
So I think this issue is not required any more. @Apollon77 what do you think?

**Comment by Apollon77** [comment]
yes, e will do new ines when we find new needs
